using BontempzGeography.Structs;

namespace BontempzGeography.DataSource
{
    public class States
    {
        public static List<State> GetByCountryCode(string countryCode)
        {
            if(CheckCountryCodes(countryCode))
            { 
                return GetStates().Where(_ => _.CountryCode == countryCode).ToList();
            }
            else
            {
                return new List<State>();
            }
        }

        private static List<State> GetStates()
        {
            var states = new List<State>()
            {
new State("AD", "07", "Andorra la Vella"),
new State("AD", "02", "Canillo"),
new State("AD", "03", "Encamp"),
new State("AD", "08", "Escaldes-Engordany"),
new State("AD", "04", "La Massana"),
new State("AD", "05", "Ordino"),
new State("AD", "06", "Sant Julia de Loria"),
new State("AE", "AZ", "Abu Dhabi"),
new State("AE", "AJ", "Ajman"),
new State("AE", "DU", "Dubai"),
new State("AE", "FU", "Fujairah"),
new State("AE", "RK", "Ras al-Khaimah"),
new State("AE", "SH", "Sharjah"),
new State("AE", "UQ", "Umm al-Quwain"),
new State("AG", "BA", "Barbuda"),
new State("AG", "RE", "Redonda"),
new State("AG", "SG", "Saint George"),
new State("AG", "SJ", "Saint John"),
new State("AG", "SM", "Saint Mary"),
new State("AG", "PA", "Saint Paul"),
new State("AG", "PE", "Saint Peter"),
new State("AG", "PH", "Saint Phillip"),
new State("AL", "01", "Berat"),
new State("AL", "09", "Dibar"),
new State("AL", "02", "Durras"),
new State("AL", "03", "Elbasan"),
new State("AL", "04", "Fier"),
new State("AL", "05", "Gjirokastar"),
new State("AL", "06", "Korca"),
new State("AL", "07", "Kukas"),
new State("AL", "08", "Lezha"),
new State("AL", "10", "Shkodar"),
new State("AL", "11", "Tirana"),
new State("AL", "12", "Vlora"),
new State("AR", "BA", "Buenos Aires"),
new State("AR", "CT", "Catamarca"),
new State("AR", "CC", "Chaco"),
new State("AR", "CH", "Chubut"),
new State("AR", "DF", "Ciudad de Buenos Aires"),
new State("AR", "CB", "Cordoba"),
new State("AR", "CN", "Corrientes"),
new State("AR", "ER", "Entre Rios"),
new State("AR", "FM", "Formosa"),
new State("AR", "JY", "Jujuy"),
new State("AR", "LP", "La Pampa"),
new State("AR", "LR", "La Rioja"),
new State("AR", "MZ", "Mendoza"),
new State("AR", "MN", "Misiones"),
new State("AR", "NQ", "Neuquen"),
new State("AR", "RN", "Rio Negro"),
new State("AR", "SA", "Salta"),
new State("AR", "SJ", "San Juan"),
new State("AR", "SL", "San Luis"),
new State("AR", "SC", "Santa Cruz"),
new State("AR", "SF", "Santa Fe"),
new State("AR", "SE", "Santiago del Estero"),
new State("AR", "TF", "Tierra del Fuego"),
new State("AR", "TM", "Tucuman"),
new State("AT", "1", "Burgenland"),
new State("AT", "2", "Carinthia"),
new State("AT", "3", "Lower Austria"),
new State("AT", "5", "Salzburg"),
new State("AT", "6", "Styria"),
new State("AT", "7", "Tyrol"),
new State("AT", "4", "Upper Austria"),
new State("AT", "9", "Vienna"),
new State("AT", "8", "Vorarlberg"),
new State("AU", "ACT", "Australian Capital Territory"),
new State("AU", "NSW", "New South Wales"),
new State("AU", "NT", "Northern Territory"),
new State("AU", "QLD", "Queensland"),
new State("AU", "SA", "South Australia"),
new State("AU", "TAS", "Tasmania"),
new State("AU", "VIC", "Victoria"),
new State("AU", "WA", "Western Australia"),
new State("BA", "BIH", "Bosnia and Herzegovina"),
new State("BA", "BRC", "Brcko District"),
new State("BA", "SRP", "Serb Republic"),
new State("BE", "VAN", "Antwerp"),
new State("BE", "BRU", "Brussels"),
new State("BE", "VOV", "East Flanders"),
new State("BE", "VBR", "Flemish Brabant"),
new State("BE", "WHT", "Hainaut"),
new State("BE", "WLG", "Liege"),
new State("BE", "VLI", "Limburg"),
new State("BE", "WLX", "Luxembourg"),
new State("BE", "WNA", "Namur"),
new State("BE", "WBR", "Walloon Brabant"),
new State("BE", "VWV", "West Flanders"),
new State("BG", "01", "Blagoevgrad"),
new State("BG", "02", "Burgas"),
new State("BG", "08", "Dobrich"),
new State("BG", "07", "Gabrovo"),
new State("BG", "22", "Grad Sofiya"),
new State("BG", "26", "Khaskovo"),
new State("BG", "09", "Kurdzhali"),
new State("BG", "10", "Kyustendil"),
new State("BG", "11", "Lovech"),
new State("BG", "12", "Montana"),
new State("BG", "13", "Pazardzhik"),
new State("BG", "14", "Pernik"),
new State("BG", "15", "Pleven"),
new State("BG", "16", "Plovdiv"),
new State("BG", "17", "Razgrad"),
new State("BG", "18", "Ruse"),
new State("BG", "27", "Shumen"),
new State("BG", "19", "Silistra"),
new State("BG", "20", "Sliven"),
new State("BG", "21", "Smolyan"),
new State("BG", "23", "Sofiya"),
new State("BG", "24", "Stara Zagora"),
new State("BG", "25", "Turgovishte"),
new State("BG", "03", "Varna"),
new State("BG", "04", "Veliko Turnovo"),
new State("BG", "05", "Vidin"),
new State("BG", "06", "Vratsa"),
new State("BG", "28", "Yambol"),
new State("BO", "B", "Beni"),
new State("BO", "H", "Chuquisaca"),
new State("BO", "C", "Cochabamba"),
new State("BO", "L", "La Paz"),
new State("BO", "O", "Oruro"),
new State("BO", "N", "Pando"),
new State("BO", "P", "Potosi"),
new State("BO", "S", "Santa Cruz"),
new State("BO", "T", "Tarija"),
new State("BR", "AC", "Acre"),
new State("BR", "AL", "Alagoas"),
new State("BR", "AP", "Amapa"),
new State("BR", "AM", "Amazonas"),
new State("BR", "BA", "Bahia"),
new State("BR", "CE", "Ceara"),
new State("BR", "BR", "Distrito Federal"),
new State("BR", "ES", "Espirito Santo"),
new State("BR", "GO", "Goias"),
new State("BR", "MA", "Maranhao"),
new State("BR", "MT", "Mato Grosso"),
new State("BR", "MS", "Mato Grosso do Sul"),
new State("BR", "MG", "Minas Gerais"),
new State("BR", "PA", "Para"),
new State("BR", "PB", "Paraiba"),
new State("BR", "PR", "Parana"),
new State("BR", "PE", "Pernambuco"),
new State("BR", "PI", "Piaui"),
new State("BR", "RJ", "Rio de Janeiro"),
new State("BR", "RN", "Rio Grande do Norte"),
new State("BR", "RS", "Rio Grande do Sul"),
new State("BR", "RO", "Rondonia"),
new State("BR", "RR", "Roraima"),
new State("BR", "SC", "Santa Catarina"),
new State("BR", "SP", "Sao Paulo"),
new State("BR", "SE", "Sergipe"),
new State("BR", "TO", "Tocantins"),
new State("BS", "AK", "Acklins"),
new State("BS", "BY", "Berry Islands"),
new State("BS", "BI", "Bimini"),
new State("BS", "BP", "Black Point"),
new State("BS", "CI", "Cat Island"),
new State("BS", "CO", "Central Abaco"),
new State("BS", "CS", "Central Andros"),
new State("BS", "CE", "Central Eleuthera"),
new State("BS", "FP", "City of Freeport"),
new State("BS", "CK", "Crooked Island and Long Cay"),
new State("BS", "EG", "East Grand Bahama"),
new State("BS", "EX", "Exuma"),
new State("BS", "GC", "Grand Cay"),
new State("BS", "HI", "Harbour Island"),
new State("BS", "HT", "Hope Town"),
new State("BS", "IN", "Inagua"),
new State("BS", "LI", "Long Island"),
new State("BS", "MC", "Mangrove Cay"),
new State("BS", "MG", "Mayaguana"),
new State("BS", "MI", "Moores Island"),
new State("BS", "NP", "New Province"),
new State("BS", "NO", "North Abaco"),
new State("BS", "NS", "North Andros"),
new State("BS", "NE", "North Eleuthera"),
new State("BS", "RI", "Ragged Island"),
new State("BS", "RC", "Rum Cay"),
new State("BS", "SS", "San Salvador"),
new State("BS", "SO", "South Abaco"),
new State("BS", "SA", "South Andros"),
new State("BS", "SE", "South Eleuthera"),
new State("BS", "SW", "Spanish Wells"),
new State("BS", "WG", "West Grand Bahama"),
new State("BW", "CE", "Central"),
new State("BW", "CH", "Chobe"),
new State("BW", "FR", "Francistown"),
new State("BW", "GA", "Gaborone"),
new State("BW", "GH", "Ghanzi"),
new State("BW", "JW", "Jwaneng"),
new State("BW", "KG", "Kgalagadi"),
new State("BW", "KL", "Kgatleng"),
new State("BW", "KW", "Kweneng"),
new State("BW", "LO", "Lobatse"),
new State("BW", "NE", "North East"),
new State("BW", "NW", "North West"),
new State("BW", "SP", "Selibe Phikwe"),
new State("BW", "SE", "South East"),
new State("BW", "SO", "Southern"),
new State("BW", "ST", "Sowa Town"),
new State("BY", "BR", "Brest Oblast"),
new State("BY", "HO", "Gomel Oblast"),
new State("BY", "HR", "Grodno Oblast"),
new State("BY", "HM", "Minsk (Municipality)"),
new State("BY", "MI", "Minsk Oblast"),
new State("BY", "MA", "Mogilev Oblast"),
new State("BY", "VI", "Vitibsk Oblast"),
new State("BZ", "BZ", "Belize"),
new State("BZ", "CY", "Cayo"),
new State("BZ", "CZL", "Corozal"),
new State("BZ", "OW", "Orange Walk"),
new State("BZ", "SC", "Stann Creek"),
new State("BZ", "TOL", "Toledo"),
new State("CA", "AB", "Alberta"),
new State("CA", "BC", "British Columbia"),
new State("CA", "MB", "Manitoba"),
new State("CA", "NB", "New Brunswick"),
new State("CA", "NL", "Newfoundland and Labrador"),
new State("CA", "NT", "Northwest Territories"),
new State("CA", "NS", "Nova Scotia"),
new State("CA", "NU", "Nunavut"),
new State("CA", "ON", "Ontario"),
new State("CA", "PE", "Prince Edward Island"),
new State("CA", "QC", "Quebec"),
new State("CA", "SK", "Saskatchewan"),
new State("CA", "YT", "Yukon Territory"),
new State("CH", "AG", "Aargau"),
new State("CH", "AR", "Appenzell Ausserrhoden"),
new State("CH", "AI", "Appenzell Innerrhoden"),
new State("CH", "BL", "Basel-Landschaft"),
new State("CH", "BS", "Basel-Stadt"),
new State("CH", "BE", "Bern"),
new State("CH", "FR", "Fribourg"),
new State("CH", "GE", "Geneva"),
new State("CH", "GL", "Glarus"),
new State("CH", "GR", "Grisons"),
new State("CH", "JU", "Jura"),
new State("CH", "LU", "Luzern"),
new State("CH", "NE", "Neuchatel"),
new State("CH", "NW", "Nidwalden"),
new State("CH", "OW", "Obwalden"),
new State("CH", "SH", "Schaffhausen"),
new State("CH", "SZ", "Schwyz"),
new State("CH", "SO", "Solothurn"),
new State("CH", "SG", "St. Gallen"),
new State("CH", "TG", "Thurgau"),
new State("CH", "TI", "Ticino"),
new State("CH", "UR", "Uri"),
new State("CH", "VS", "Valais"),
new State("CH", "VD", "Vaud"),
new State("CH", "ZG", "Zug"),
new State("CH", "ZH", "Zurich"),
new State("CL", "AI", "Aisen del General Carlos Ibanez del Campo"),
new State("CL", "AN", "Antofagasta"),
new State("CL", "AP", "Arica y Parinacota"),
new State("CL", "AT", "Atacama"),
new State("CL", "BI", "Biobio"),
new State("CL", "CO", "Coquimbo"),
new State("CL", "AR", "La Araucania"),
new State("CL", "LI", "Libertador General Bernardo O'Higgins"),
new State("CL", "LL", "Los Lagos"),
new State("CL", "LR", "Los Rios"),
new State("CL", "MA", "Magallanes"),
new State("CL", "ML", "Maule"),
new State("CL", "NU", "Nuble"),
new State("CL", "RM", "Santiago, Metropolitan Region"),
new State("CL", "TA", "Tarapaca"),
new State("CL", "VS", "Valparaiso"),
new State("CN", "AH", "Anhui Province"),
new State("CN", "BJ", "Beijing Municipality"),
new State("CN", "CQ", "Chongqing Municipality"),
new State("CN", "FJ", "Fujian Province"),
new State("CN", "GS", "Gansu Province"),
new State("CN", "GD", "Guangdong Province"),
new State("CN", "GX", "Guangxi Zhuang Autonomous Region"),
new State("CN", "GZ", "Guizhou Province"),
new State("CN", "HI", "Hainan Province"),
new State("CN", "HE", "Hebei Province"),
new State("CN", "HL", "Heilongjiang Province"),
new State("CN", "HA", "Henan Province"),
new State("CN", "HK", "Hong Kong Special Administrative Region"),
new State("CN", "HB", "Hubei Province"),
new State("CN", "HN", "Hunan Province"),
new State("CN", "NM", "Inner Mongolia Autonomous Region"),
new State("CN", "JS", "Jiangsu Province"),
new State("CN", "JX", "Jiangxi Province"),
new State("CN", "JL", "Jilin Province"),
new State("CN", "LN", "Liaoning Province"),
new State("CN", "MO", "Macau Special Administrative Region"),
new State("CN", "NX", "Ningxia Hui Autonomous Region"),
new State("CN", "QH", "Qinghai Province"),
new State("CN", "SN", "Shaanxi Province"),
new State("CN", "SD", "Shandong Province"),
new State("CN", "SH", "Shanghai Municipality"),
new State("CN", "SX", "Shanxi Province"),
new State("CN", "SC", "Sichuan Province"),
new State("CN", "TW", "Taiwan Province"),
new State("CN", "TJ", "Tianjin Municipality"),
new State("CN", "XZ", "Tibet Autonomous Region"),
new State("CN", "XJ", "Xinjiang Uyghur Autonomous Region"),
new State("CN", "YN", "Yunnan Province"),
new State("CN", "ZJ", "Zhejiang Province"),
new State("CO", "AMA", "Amazonas"),
new State("CO", "ANT", "Antioquia"),
new State("CO", "ARA", "Arauca"),
new State("CO", "ATL", "Atlantico"),
new State("CO", "BOL", "Bolivar"),
new State("CO", "BOY", "Boyaca"),
new State("CO", "CAL", "Caldas"),
new State("CO", "CAQ", "Caqueta"),
new State("CO", "CAS", "Casanare"),
new State("CO", "CAU", "Cauca"),
new State("CO", "CES", "Cesar"),
new State("CO", "CHO", "Choco"),
new State("CO", "COR", "Cordoba"),
new State("CO", "CUN", "Cundinamarca"),
new State("CO", "GUA", "Guainia"),
new State("CO", "GUV", "Guaviare"),
new State("CO", "HUI", "Huila"),
new State("CO", "LAG", "La Guajira"),
new State("CO", "MAG", "Magdalena"),
new State("CO", "MET", "Meta"),
new State("CO", "NAR", "Narino"),
new State("CO", "NOR", "Norte De Santander"),
new State("CO", "PUT", "Putumayo"),
new State("CO", "QUI", "Quindio"),
new State("CO", "RIS", "Risaralda"),
new State("CO", "SAN", "San Andres"),
new State("CO", "SNT", "Santander"),
new State("CO", "SUC", "Sucre"),
new State("CO", "TOL", "Tolima"),
new State("CO", "VAL", "Valle Del Cauca"),
new State("CO", "VAU", "Vaupes"),
new State("CO", "VIC", "Vichada"),
new State("CR", "A", "Alajuela"),
new State("CR", "C", "Cartago"),
new State("CR", "G", "Guanacaste"),
new State("CR", "H", "Heredia"),
new State("CR", "L", "Limon"),
new State("CR", "P", "Puntarenas"),
new State("CR", "SJ", "San Jose"),
new State("CU", "15", "Artemisa"),
new State("CU", "09", "Camaguey"),
new State("CU", "08", "Ciego de Avila"),
new State("CU", "06", "Cienfuegos"),
new State("CU", "12", "Granma"),
new State("CU", "14", "Guantanamo"),
new State("CU", "03", "Habana"),
new State("CU", "11", "Holguin"),
new State("CU", "99", "Isla de la Juventud"),
new State("CU", "10", "Las Tunas"),
new State("CU", "04", "Matanzas"),
new State("CU", "01", "Pinar del Rio"),
new State("CU", "07", "Sancti Spiritus"),
new State("CU", "13", "Santiago de Cuba"),
new State("CU", "05", "Villa Clara"),
new State("CV", "BV", "Boa Vista"),
new State("CV", "BR", "Brava"),
new State("CV", "MA", "Maio"),
new State("CV", "MO", "Mosteiros"),
new State("CV", "PA", "Paul"),
new State("CV", "PN", "Porto Novo"),
new State("CV", "PR", "Praia"),
new State("CV", "RB", "Ribeira Brava"),
new State("CV", "RG", "Ribeira Grande"),
new State("CV", "RS", "Ribeira Grande de Santiago"),
new State("CV", "SL", "Sal"),
new State("CV", "CA", "Santa Catarina"),
new State("CV", "CF", "Santa Catarina do Fogo"),
new State("CV", "CR", "Santa Cruz"),
new State("CV", "SD", "Sao Domingos"),
new State("CV", "SF", "Sao Filipe"),
new State("CV", "SO", "Sao Lourenço dos Orgãos"),
new State("CV", "SM", "Sao Miguel"),
new State("CV", "SS", "Sao Salvador do Mundo"),
new State("CV", "SV", "Sao Vicente"),
new State("CV", "TA", "Tarrafal"),
new State("CV", "TS", "Tarrafal de Sao Nicolau"),
new State("CY", "04", "Famagusta"),
new State("CY", "06", "Kyrenia"),
new State("CY", "03", "Larnaca"),
new State("CY", "02", "Limassol"),
new State("CY", "01", "Nicosia"),
new State("CY", "05", "Paphos"),
new State("CZ", "20", "Central Bohemia"),
new State("CZ", "52", "Hradec Kralove"),
new State("CZ", "41", "Karlovy Vary"),
new State("CZ", "51", "Liberec"),
new State("CZ", "80", "Moravia-Silesia"),
new State("CZ", "71", "Olomouc"),
new State("CZ", "53", "Pardubice"),
new State("CZ", "32", "Plzen"),
new State("CZ", "10", "Prague"),
new State("CZ", "31", "South Bohemia"),
new State("CZ", "64", "South Moravia"),
new State("CZ", "42", "Usti nad Labem"),
new State("CZ", "63", "Vysocina"),
new State("CZ", "72", "Zlin"),
new State("DC", "BAS", "Bas-Uele"),
new State("DC", "EQU", "Equateur"),
new State("DC", "HAK", "Haut-Katanga"),
new State("DC", "HAL", "Haut-Lomami"),
new State("DC", "HAU", "Haut-Uele"),
new State("DC", "ITU", "Ituri"),
new State("DC", "KAS", "Kasai"),
new State("DC", "KAC", "Kasai-Central"),
new State("DC", "KAO", "Kasai-Oriental"),
new State("DC", "KIN", "Kinshasa"),
new State("DC", "KON", "Kongo Central"),
new State("DC", "KWA", "Kwango"),
new State("DC", "KWI", "Kwilu"),
new State("DC", "LOM", "Lomami"),
new State("DC", "LUA", "Lualaba"),
new State("DC", "MAI", "Mai-Ndombe"),
new State("DC", "MAN", "Maniema"),
new State("DC", "MON", "Mongala"),
new State("DC", "NOR", "Nord-Ubangi"),
new State("DC", "NKI", "North Kivu"),
new State("DC", "SAN", "Sankuru"),
new State("DC", "SKI", "South Kivu"),
new State("DC", "SUD", "Sud-Ubangi"),
new State("DC", "TAN", "Tanganyika"),
new State("DC", "TSO", "Tshopo"),
new State("DC", "TSA", "Tshuapa"),
new State("DE", "BW", "Baden-Wuerttemberg"),
new State("DE", "BY", "Bavaria"),
new State("DE", "BE", "Berlin"),
new State("DE", "BB", "Brandenburg"),
new State("DE", "HB", "Bremen"),
new State("DE", "HH", "Hamburg"),
new State("DE", "HE", "Hesse"),
new State("DE", "NI", "Lower Saxony"),
new State("DE", "MV", "Mecklenburg-Vorpommern"),
new State("DE", "NW", "North Rhine-Westphalia"),
new State("DE", "RP", "Rhineland-Palatinate"),
new State("DE", "SL", "Saarland"),
new State("DE", "SN", "Saxony"),
new State("DE", "ST", "Saxony-Anhalt"),
new State("DE", "SH", "Schleswig-Holstein"),
new State("DE", "TH", "Thuringia"),
new State("DK", "84", "Capital"),
new State("DK", "82", "Central Jutland"),
new State("DK", "81", "North Jutland"),
new State("DK", "83", "South Denmark"),
new State("DK", "85", "Zealand"),
new State("DM", "02", "Saint Andrew"),
new State("DM", "03", "Saint David"),
new State("DM", "04", "Saint George"),
new State("DM", "05", "Saint John"),
new State("DM", "06", "Saint Joseph"),
new State("DM", "07", "Saint Luke"),
new State("DM", "08", "Saint Mark"),
new State("DM", "09", "Saint Patrick"),
new State("DM", "10", "Saint Paul"),
new State("DM", "11", "Saint Peter"),
new State("DO", "02", "Azua"),
new State("DO", "03", "Bahoruco"),
new State("DO", "04", "Barahona"),
new State("DO", "05", "Dajabon"),
new State("DO", "06", "Duarte"),
new State("DO", "08", "El Seibo"),
new State("DO", "07", "Elias Pina"),
new State("DO", "09", "Espaillat"),
new State("DO", "30", "Hato Mayor"),
new State("DO", "19", "Hermanas Mirabal"),
new State("DO", "10", "Independencia"),
new State("DO", "11", "La Altagracia"),
new State("DO", "12", "La Romana"),
new State("DO", "13", "La Vega"),
new State("DO", "14", "Maria Trinidad Sanchez"),
new State("DO", "01", "National District"),
new State("DZ", "01", "Adrar"),
new State("DZ", "44", "Ain Defla"),
new State("DZ", "46", "Ain Temouchent"),
new State("DZ", "16", "Algiers"),
new State("DZ", "23", "Annaba"),
new State("DZ", "05", "Batna"),
new State("DZ", "08", "Bechar"),
new State("DZ", "06", "Bejaia"),
new State("DZ", "07", "Biskra"),
new State("DZ", "09", "Blida"),
new State("DZ", "34", "Bordj Bou Arréridj"),
new State("DZ", "10", "Bouira"),
new State("DZ", "35", "Boumerdes"),
new State("DZ", "02", "Chlef"),
new State("DZ", "25", "Constantine"),
new State("DZ", "17", "Djelfa"),
new State("DZ", "32", "El Bayadh"),
new State("DZ", "39", "El Oued"),
new State("DZ", "36", "El Taref"),
new State("DZ", "47", "Ghardaia"),
new State("DZ", "24", "Guelma"),
new State("DZ", "33", "Illizi"),
new State("DZ", "18", "Jijel"),
new State("DZ", "40", "Khenchela"),
new State("DZ", "03", "Laghouat"),
new State("DZ", "29", "Mascara"),
new State("DZ", "26", "Medea"),
new State("DZ", "43", "Mila"),
new State("DZ", "27", "Mostaganem"),
new State("DZ", "28", "M'Sila"),
new State("DZ", "45", "Naama"),
new State("DZ", "31", "Oran"),
new State("DZ", "30", "Ouargla"),
new State("DZ", "04", "Oum el-Bouaghi"),
new State("DZ", "48", "Relizane"),
new State("DZ", "20", "Saida"),
new State("DZ", "19", "Setif"),
new State("DZ", "22", "Sidi Bel Abbes"),
new State("DZ", "21", "Skikda"),
new State("DZ", "41", "Souk Ahras"),
new State("DZ", "11", "Tamanghasset"),
new State("DZ", "12", "Tebessa"),
new State("DZ", "14", "Tiaret"),
new State("DZ", "37", "Tindouf"),
new State("DZ", "42", "Tipaza"),
new State("DZ", "38", "Tissemsilt"),
new State("DZ", "15", "Tizi Ouzou"),
new State("DZ", "13", "Tlemcen"),
new State("EC", "A", "Azuay"),
new State("EC", "B", "Bolivar"),
new State("EC", "F", "Canar"),
new State("EC", "C", "Carchi"),
new State("EC", "H", "Chimborazo"),
new State("EC", "X", "Cotopaxi"),
new State("EC", "O", "El Oro"),
new State("EC", "E", "Esmeraldas"),
new State("EC", "W", "Galapagos"),
new State("EC", "G", "Guayas"),
new State("EC", "I", "Imbabura"),
new State("EC", "L", "Loja"),
new State("EC", "R", "Los Rios"),
new State("EC", "M", "Manabi"),
new State("EC", "S", "Morona Santiago"),
new State("EC", "N", "Napo"),
new State("EC", "D", "Orellana"),
new State("EC", "Y", "Pastaza"),
new State("EC", "P", "Pichincha"),
new State("EC", "SE", "Santa Elena"),
new State("EC", "SD", "Santo Domingo de los Tsachilas"),
new State("EC", "U", "Sucumbios"),
new State("EC", "T", "Tungurahua"),
new State("EC", "Z", "Zamora-Chinchipe"),
new State("EE", "37", "Harju"),
new State("EE", "39", "Hiiu"),
new State("EE", "44", "Ida-Viru"),
new State("EE", "51", "Jarva"),
new State("EE", "49", "Jogeva"),
new State("EE", "57", "Laane"),
new State("EE", "59", "Laane-Viru"),
new State("EE", "67", "Parnu"),
new State("EE", "65", "Polva"),
new State("EE", "70", "Rapla"),
new State("EE", "74", "Saare"),
new State("EE", "78", "Tartu"),
new State("EE", "82", "Valga"),
new State("EE", "84", "Viljandi"),
new State("EE", "86", "Voru"),
new State("EG", "SHR", "Al Sharqia"),
new State("EG", "ALX", "Alexandria"),
new State("EG", "ASN", "Aswan"),
new State("EG", "AST", "Asyut"),
new State("EG", "BH", "Beheira"),
new State("EG", "BNS", "Beni Suef"),
new State("EG", "C", "Cairo"),
new State("EG", "DK", "Dakahlia"),
new State("EG", "DT", "Damietta"),
new State("EG", "FYM", "Faiyum"),
new State("EG", "GH", "Gharbia"),
new State("EG", "GZ", "Giza"),
new State("EG", "IS", "Ismailia"),
new State("EG", "KFS", "Kafr el-Sheikh"),
new State("EG", "LX", "Luxor"),
new State("EG", "MT", "Matrouh"),
new State("EG", "MN", "Minya"),
new State("EG", "MNF", "Monufia"),
new State("EG", "WAD", "New Valley"),
new State("EG", "SIN", "North Sinai"),
new State("EG", "PTS", "Port Said"),
new State("EG", "KB", "Qalyubia"),
new State("EG", "BA", "Red Sea"),
new State("EG", "SHG", "Sohag"),
new State("EG", "JS", "South Sinai"),
new State("EG", "SUZ", "Suez"),
new State("ES", "C", "A Coruna"),
new State("ES", "VI", "Alava"),
new State("ES", "AB", "Albacete"),
new State("ES", "A", "Alicante"),
new State("ES", "AL", "Almeria"),
new State("ES", "O", "Asturias"),
new State("ES", "AV", "Avila"),
new State("ES", "BA", "Badajoz"),
new State("ES", "PM", "Balears"),
new State("ES", "B", "Barcelona"),
new State("ES", "BI", "Bizkaia"),
new State("ES", "BU", "Burgos"),
new State("ES", "CC", "Caceres"),
new State("ES", "CA", "Cadiz"),
new State("ES", "S", "Cantabria"),
new State("ES", "CS", "Castellon"),
new State("ES", "CE", "Ceuta"),
new State("ES", "CR", "Ciudad Real"),
new State("ES", "CO", "Cordoba"),
new State("ES", "CU", "Cuenca"),
new State("ES", "SS", "Gipuzkoa"),
new State("ES", "GI", "Girona"),
new State("ES", "GR", "Granada"),
new State("ES", "GU", "Guadalajara"),
new State("ES", "H", "Huelva"),
new State("ES", "HU", "Huesca"),
new State("ES", "J", "Jaen"),
new State("ES", "LO", "La Rioja"),
new State("ES", "GC", "Las Palmas"),
new State("ES", "LE", "Leon"),
new State("ES", "L", "Lleida"),
new State("ES", "LU", "Lugo"),
new State("ES", "M", "Madrid"),
new State("ES", "MA", "Malaga"),
new State("ES", "ML", "Melilla"),
new State("ES", "MU", "Murcia"),
new State("ES", "NA", "Navarra"),
new State("ES", "OR", "Ourense"),
new State("ES", "P", "Palencia"),
new State("ES", "PO", "Pontevedra"),
new State("ES", "SA", "Salamanca"),
new State("ES", "TF", "Santa Cruz de Tenerife"),
new State("ES", "SG", "Segovia"),
new State("ES", "SE", "Sevilla"),
new State("ES", "SO", "Soria"),
new State("ES", "T", "Tarragona"),
new State("ES", "TE", "Teruel"),
new State("ES", "TO", "Toledo"),
new State("ES", "V", "Valencia"),
new State("ES", "VA", "Valladolid"),
new State("ES", "ZA", "Zamora"),
new State("ES", "Z", "Zaragoza"),
new State("FI", "01", "Aland"),
new State("FI", "08", "Central Finland"),
new State("FI", "07", "Central Ostrobothnia"),
new State("FI", "05", "Kainuu"),
new State("FI", "09", "Kymenlaakso"),
new State("FI", "10", "Lapland"),
new State("FI", "13", "North Karelia"),
new State("FI", "14", "North Ostrobothnia"),
new State("FI", "15", "North Savonia"),
new State("FI", "12", "Ostrobothnia"),
new State("FI", "16", "Paijanne Tavastia"),
new State("FI", "17", "Satakunta"),
new State("FI", "02", "South Karelia"),
new State("FI", "03", "South Ostrobothnia"),
new State("FI", "04", "South Savonia"),
new State("FI", "19", "Southwest Finland"),
new State("FI", "11", "Tampere Region"),
new State("FI", "06", "Tavastia Proper"),
new State("FI", "18", "Uusimaa"),
new State("FJ", "01", "Ba"),
new State("FJ", "02", "Bua"),
new State("FJ", "03", "Cakaudrove"),
new State("FJ", "04", "Kadavu"),
new State("FJ", "05", "Lau"),
new State("FJ", "06", "Lomaiviti"),
new State("FJ", "07", "Macuata"),
new State("FJ", "08", "Nadroga-Navosa"),
new State("FJ", "09", "Naitasiri"),
new State("FJ", "10", "Namosi"),
new State("FJ", "11", "Ra"),
new State("FJ", "12", "Rewa"),
new State("FJ", "R", "Rotuma"),
new State("FJ", "13", "Serua"),
new State("FJ", "14", "Tailevu"),
new State("FM", "TRK", "Chuuk"),
new State("FM", "KSA", "Kosrae"),
new State("FM", "PNI", "Pohnpei"),
new State("FM", "YAP", "Yap"),
new State("FR", "01", "Ain"),
new State("FR", "02", "Aisne"),
new State("FR", "03", "Allier"),
new State("FR", "04", "Alpes-de-Haute-Provence"),
new State("FR", "06", "Alpes-Maritimes"),
new State("FR", "07", "Ardeche"),
new State("FR", "08", "Ardennes"),
new State("FR", "09", "Ariege"),
new State("FR", "10", "Aube"),
new State("FR", "11", "Aude"),
new State("FR", "12", "Aveyron"),
new State("FR", "67", "Bas-Rhin"),
new State("FR", "13", "Bouches-du-Rhone"),
new State("FR", "14", "Calvados"),
new State("FR", "15", "Cantal"),
new State("FR", "16", "Charente"),
new State("FR", "17", "Charente-Maritime"),
new State("FR", "18", "Cher"),
new State("FR", "19", "Correze"),
new State("FR", "20", "Corse"),
new State("FR", "21", "Cote-d'Or"),
new State("FR", "22", "Cotes-d'Armor"),
new State("FR", "23", "Creuse"),
new State("FR", "79", "Deux-Sevres"),
new State("FR", "24", "Dordogne"),
new State("FR", "25", "Doubs"),
new State("FR", "26", "Drome"),
new State("FR", "91", "Essonne"),
new State("FR", "27", "Eure"),
new State("FR", "28", "Eure-et-Loir"),
new State("FR", "29", "Finistere"),
new State("FR", "30", "Gard"),
new State("FR", "32", "Gers"),
new State("FR", "33", "Gironde"),
new State("FR", "971", "Guadeloupe"),
new State("FR", "973", "Guyane"),
new State("FR", "31", "Haute-Garonne"),
new State("FR", "43", "Haute-Loire"),
new State("FR", "52", "Haute-Marne"),
new State("FR", "05", "Hautes-Alpes"),
new State("FR", "70", "Haute-Saone"),
new State("FR", "74", "Haute-Savoie"),
new State("FR", "65", "Hautes-Pyrenees"),
new State("FR", "87", "Haute-Vienne"),
new State("FR", "68", "Haut-Rhin"),
new State("FR", "92", "Hauts-de-Seine"),
new State("FR", "34", "Herault"),
new State("FR", "35", "Ille-et-Vilaine"),
new State("FR", "36", "Indre"),
new State("FR", "37", "Indre-et-Loire"),
new State("FR", "38", "Isere"),
new State("FR", "39", "Jura"),
new State("FR", "974", "La Reunion"),
new State("FR", "40", "Landes"),
new State("FR", "42", "Loire"),
new State("FR", "44", "Loire-Atlantique"),
new State("FR", "45", "Loiret"),
new State("FR", "41", "Loir-et-Cher"),
new State("FR", "46", "Lot"),
new State("FR", "47", "Lot-et-Garonne"),
new State("FR", "48", "Lozere"),
new State("FR", "69M", "Lyon Metropolis"),
new State("FR", "49", "Maine-et-Loire"),
new State("FR", "50", "Manche"),
new State("FR", "51", "Marne"),
new State("FR", "972", "Martinique"),
new State("FR", "53", "Mayenne"),
new State("FR", "976", "Mayotte"),
new State("FR", "54", "Meurthe-et-Moselle"),
new State("FR", "55", "Meuse"),
new State("FR", "56", "Morbihan"),
new State("FR", "57", "Moselle"),
new State("FR", "58", "Nievre"),
new State("FR", "59", "Nord"),
new State("FR", "60", "Oise"),
new State("FR", "61", "Orne"),
new State("FR", "75", "Paris"),
new State("FR", "62", "Pas-de-Calais"),
new State("FR", "63", "Puy-de-Dome"),
new State("FR", "64", "Pyrenees-Atlantiques"),
new State("FR", "66", "Pyrenees-Orientales"),
new State("FR", "69", "Rhone"),
new State("FR", "71", "Saone-et-Loire"),
new State("FR", "72", "Sarthe"),
new State("FR", "73", "Savoie"),
new State("FR", "77", "Seine-et-Marne"),
new State("FR", "76", "Seine-Maritime"),
new State("FR", "93", "Seine-Saint-Denis"),
new State("FR", "80", "Somme"),
new State("FR", "81", "Tarn"),
new State("FR", "82", "Tarn-et-Garonne"),
new State("FR", "90", "Territoire de Belfort"),
new State("FR", "94", "Val-de-Marne"),
new State("FR", "95", "Val-d'Oise"),
new State("FR", "83", "Var"),
new State("FR", "84", "Vaucluse"),
new State("FR", "85", "Vendee"),
new State("FR", "86", "Vienne"),
new State("FR", "88", "Vosges"),
new State("FR", "89", "Yonne"),
new State("FR", "78", "Yvelines"),
new State("GB", "ABE", "Aberdeen City"),
new State("GB", "ABD", "Aberdeenshire"),
new State("GB", "ANS", "Angus"),
new State("GB", "ANN", "Antrim and Newtownabbey"),
new State("GB", "AND", "Ards and North Down"),
new State("GB", "AGB", "Argyll and Bute"),
new State("GB", "ABC", "Armagh, Banbridge and Craigavon"),
new State("GB", "BDG", "Barking and Dagenham"),
new State("GB", "BNE", "Barnet"),
new State("GB", "BNS", "Barnsley"),
new State("GB", "BAS", "Bath and North East Somerset"),
new State("GB", "BDF", "Bedford"),
new State("GB", "BFS", "Belfast"),
new State("GB", "BEX", "Bexley"),
new State("GB", "BIR", "Birmingham"),
new State("GB", "BBD", "Blackburn with Darwen"),
new State("GB", "BPL", "Blackpool"),
new State("GB", "BGW", "Blaenau Gwent"),
new State("GB", "BOL", "Bolton"),
new State("GB", "BMH", "Bournemouth"),
new State("GB", "BRC", "Bracknell Forest"),
new State("GB", "BRD", "Bradford"),
new State("GB", "BEN", "Brent"),
new State("GB", "BGE", "Bridgend"),
new State("GB", "BNH", "Brighton and Hove"),
new State("GB", "BST", "Bristol, City of"),
new State("GB", "BRY", "Bromley"),
new State("GB", "BKM", "Buckinghamshire"),
new State("GB", "BUR", "Bury"),
new State("GB", "CAY", "Caerphilly"),
new State("GB", "CLD", "Calderdale"),
new State("GB", "CAM", "Cambridgeshire"),
new State("GB", "CMD", "Camden"),
new State("GB", "CRF", "Cardiff"),
new State("GB", "CMN", "Carmarthenshire"),
new State("GB", "CCG", "Causeway Coast and Glens"),
new State("GB", "CBF", "Central Bedfordshire"),
new State("GB", "CGN", "Ceredigion"),
new State("GB", "CHE", "Cheshire East"),
new State("GB", "CHW", "Cheshire West and Chester"),
new State("GB", "CLK", "Clackmannanshire"),
new State("GB", "CWY", "Conwy"),
new State("GB", "CON", "Cornwall"),
new State("GB", "COV", "Coventry"),
new State("GB", "CRY", "Croydon"),
new State("GB", "CMA", "Cumbria"),
new State("GB", "DAL", "Darlington"),
new State("GB", "DEN", "Denbighshire"),
new State("GB", "DER", "Derby"),
new State("GB", "DBY", "Derbyshire"),
new State("GB", "DRS", "Derry and Strabane"),
new State("GB", "DEV", "Devon"),
new State("GB", "DNC", "Doncaster"),
new State("GB", "DOR", "Dorset"),
new State("GB", "DUD", "Dudley"),
new State("GB", "DGY", "Dumfries and Galloway"),
new State("GB", "DND", "Dundee City"),
new State("GB", "DUR", "Durham, County"),
new State("GB", "EAL", "Ealing"),
new State("GB", "EAY", "East Ayrshire"),
new State("GB", "EDU", "East Dunbartonshire"),
new State("GB", "ELN", "East Lothian"),
new State("GB", "ERW", "East Renfrewshire"),
new State("GB", "ERY", "East Riding of Yorkshire"),
new State("GB", "ESX", "East Sussex"),
new State("GB", "EDH", "Edinburgh, City of"),
new State("GB", "ELS", "Eilean Siar"),
new State("GB", "ENF", "Enfield"),
new State("GB", "ESS", "Essex"),
new State("GB", "FAL", "Falkirk"),
new State("GB", "FMO", "Fermanagh and Omagh"),
new State("GB", "FIF", "Fife"),
new State("GB", "FLN", "Flintshire"),
new State("GB", "GAT", "Gateshead"),
new State("GB", "GLG", "Glasgow City"),
new State("GB", "GLS", "Gloucestershire"),
new State("GB", "GRE", "Greenwich"),
new State("GB", "GWN", "Gwynedd"),
new State("GB", "HCK", "Hackney"),
new State("GB", "HAL", "Halton"),
new State("GB", "HMF", "Hammersmith and Fulham"),
new State("GB", "HAM", "Hampshire"),
new State("GB", "HRY", "Haringey"),
new State("GB", "HRW", "Harrow"),
new State("GB", "HPL", "Hartlepool"),
new State("GB", "HAV", "Havering"),
new State("GB", "HEF", "Herefordshire"),
new State("GB", "HRT", "Hertfordshire"),
new State("GB", "HLD", "Highland"),
new State("GB", "HIL", "Hillingdon"),
new State("GB", "HNS", "Hounslow"),
new State("GB", "IVC", "Inverclyde"),
new State("GB", "AGY", "Isle of Anglesey"),
new State("GB", "IOW", "Isle of Wight"),
new State("GB", "IOS", "Isles of Scilly"),
new State("GB", "ISL", "Islington"),
new State("GB", "KEC", "Kensington and Chelsea"),
new State("GB", "KEN", "Kent"),
new State("GB", "KHL", "Kingston upon Hull"),
new State("GB", "KTT", "Kingston upon Thames"),
new State("GB", "KIR", "Kirklees"),
new State("GB", "KWL", "Knowsley"),
new State("GB", "LBH", "Lambeth"),
new State("GB", "LAN", "Lancashire"),
new State("GB", "LDS", "Leeds"),
new State("GB", "LCE", "Leicester"),
new State("GB", "LEC", "Leicestershire"),
new State("GB", "LEW", "Lewisham"),
new State("GB", "LIN", "Lincolnshire"),
new State("GB", "LBC", "Lisburn and Castlereagh"),
new State("GB", "LIV", "Liverpool"),
new State("GB", "LND", "London, City of"),
new State("GB", "LUT", "Luton"),
new State("GB", "MAN", "Manchester"),
new State("GB", "MDW", "Medway"),
new State("GB", "MTY", "Merthyr Tydfil"),
new State("GB", "MRT", "Merton"),
new State("GB", "MEA", "Mid and East Antrim"),
new State("GB", "MUL", "Mid Ulster"),
new State("GB", "MDB", "Middlesbrough"),
new State("GB", "MLN", "Midlothian"),
new State("GB", "MIK", "Milton Keynes"),
new State("GB", "MON", "Monmouthshire"),
new State("GB", "MRY", "Moray"),
new State("GB", "NTL", "Neath Port Talbot"),
new State("GB", "NET", "Newcastle upon Tyne"),
new State("GB", "NWM", "Newham"),
new State("GB", "NWP", "Newport"),
new State("GB", "NMD", "Newry, Mourne and Down"),
new State("GB", "NFK", "Norfolk"),
new State("GB", "NAY", "North Ayrshire"),
new State("GB", "NEL", "North East Lincolnshire"),
new State("GB", "NLK", "North Lanarkshire"),
new State("GB", "NLN", "North Lincolnshire"),
new State("GB", "NSM", "North Somerset"),
new State("GB", "NTY", "North Tyneside"),
new State("GB", "NYK", "North Yorkshire"),
new State("GB", "NTH", "Northamptonshire"),
new State("GB", "NBL", "Northumberland"),
new State("GB", "NGM", "Nottingham"),
new State("GB", "NTT", "Nottinghamshire"),
new State("GB", "OLD", "Oldham"),
new State("GB", "ORK", "Orkney Islands"),
new State("GB", "OXF", "Oxfordshire"),
new State("GB", "PEM", "Pembrokeshire"),
new State("GB", "PKN", "Perth and Kinross"),
new State("GB", "PTE", "Peterborough"),
new State("GB", "PLY", "Plymouth"),
new State("GB", "POL", "Poole"),
new State("GB", "POR", "Portsmouth"),
new State("GB", "POW", "Powys"),
new State("GB", "RDG", "Reading"),
new State("GB", "RDB", "Redbridge"),
new State("GB", "RCC", "Redcar and Cleveland"),
new State("GB", "RFW", "Renfrewshire"),
new State("GB", "RCT", "Rhondda, Cynon, Taff"),
new State("GB", "RIC", "Richmond upon Thames"),
new State("GB", "RCH", "Rochdale"),
new State("GB", "ROT", "Rotherham"),
new State("GB", "RUT", "Rutland"),
new State("GB", "SLF", "Salford"),
new State("GB", "SAW", "Sandwell"),
new State("GB", "SCB", "Scottish Borders, The"),
new State("GB", "SFT", "Sefton"),
new State("GB", "SHF", "Sheffield"),
new State("GB", "ZET", "Shetland Islands"),
new State("GB", "SHR", "Shropshire"),
new State("GB", "SLG", "Slough"),
new State("GB", "SOL", "Solihull"),
new State("GB", "SOM", "Somerset"),
new State("GB", "SAY", "South Ayrshire"),
new State("GB", "SGC", "South Gloucestershire"),
new State("GB", "SLK", "South Lanarkshire"),
new State("GB", "STY", "South Tyneside"),
new State("GB", "STH", "Southampton"),
new State("GB", "SOS", "Southend-on-Sea"),
new State("GB", "SWK", "Southwark"),
new State("GB", "SHN", "St. Helens"),
new State("GB", "STS", "Staffordshire"),
new State("GB", "STG", "Stirling"),
new State("GB", "SKP", "Stockport"),
new State("GB", "STT", "Stockton-on-Tees"),
new State("GB", "STE", "Stoke-on-Trent"),
new State("GB", "SFK", "Suffolk"),
new State("GB", "SND", "Sunderland"),
new State("GB", "SRY", "Surrey"),
new State("GB", "STN", "Sutton"),
new State("GB", "SWA", "Swansea"),
new State("GB", "SWD", "Swindon"),
new State("GB", "TAM", "Tameside"),
new State("GB", "TFW", "Telford and Wrekin"),
new State("GB", "THR", "Thurrock"),
new State("GB", "TOB", "Torbay"),
new State("GB", "TOF", "Torfaen"),
new State("GB", "TWH", "Tower Hamlets"),
new State("GB", "TRF", "Trafford"),
new State("GB", "VGL", "Vale of Glamorgan, The"),
new State("GB", "WKF", "Wakefield"),
new State("GB", "WLL", "Walsall"),
new State("GB", "WFT", "Waltham Forest"),
new State("GB", "WND", "Wandsworth"),
new State("GB", "WRT", "Warrington"),
new State("GB", "WAR", "Warwickshire"),
new State("GB", "WBK", "West Berkshire"),
new State("GB", "WDU", "West Dunbartonshire"),
new State("GB", "WLN", "West Lothian"),
new State("GB", "WSX", "West Sussex"),
new State("GB", "WSM", "Westminster"),
new State("GB", "WGN", "Wigan"),
new State("GB", "WIL", "Wiltshire"),
new State("GB", "WNM", "Windsor and Maidenhead"),
new State("GB", "WRL", "Wirral"),
new State("GB", "WOK", "Wokingham"),
new State("GB", "WLV", "Wolverhampton"),
new State("GB", "WOR", "Worcestershire"),
new State("GB", "WRX", "Wrexham"),
new State("GB", "YOR", "York"),
new State("GD", "10", "Carriacou"),
new State("GD", "01", "Saint Andrew"),
new State("GD", "02", "Saint David"),
new State("GD", "03", "Saint George"),
new State("GD", "04", "Saint John"),
new State("GD", "05", "Saint Mark"),
new State("GD", "06", "Saint Patrick"),
new State("GL", "AK", "Avannaata"),
new State("GL", "KK", "Kujalleq"),
new State("GL", "KQ", "Qeqertalik"),
new State("GL", "QK", "Qeqqata"),
new State("GL", "KS", "Sermersooq"),
new State("GR", "AT", "Attica"),
new State("GR", "CG", "Central Greece"),
new State("GR", "CM", "Central Macedonia"),
new State("GR", "CR", "Crete"),
new State("GR", "EM", "Eastern Macedonia and Thrace"),
new State("GR", "EP", "Epirus"),
new State("GR", "II", "Ionian Islands"),
new State("GR", "NA", "North Aegean"),
new State("GR", "PE", "Peloponnese"),
new State("GR", "SA", "South Aegean"),
new State("GR", "TH", "Thessaly"),
new State("GR", "WG", "Western Greece"),
new State("GR", "WM", "Western Macedonia"),
new State("GT", "16", "Alta Verapaz"),
new State("GT", "15", "Baja Verapaz"),
new State("GT", "04", "Chimaltenango"),
new State("GT", "20", "Chiquimula"),
new State("GT", "02", "El Progreso"),
new State("GT", "05", "Escuintla"),
new State("GT", "01", "Guatemala"),
new State("GT", "13", "Huehuetenango"),
new State("GT", "18", "Izabal"),
new State("GT", "21", "Jalapa"),
new State("GT", "22", "Jutiapa"),
new State("GT", "17", "Peten"),
new State("GT", "09", "Quetzaltenango"),
new State("GT", "14", "Quiche"),
new State("GT", "11", "Retalhuleu"),
new State("GT", "03", "Sacatepequez"),
new State("GT", "12", "San Marcos"),
new State("GT", "06", "Santa Rosa"),
new State("GT", "07", "Solola"),
new State("GT", "10", "Suchitepequez"),
new State("GT", "08", "Totonicapan"),
new State("GT", "19", "Zacapa"),
new State("GY", "BA", "Barima-Waini"),
new State("GY", "CU", "Cuyuni-Mazaruni"),
new State("GY", "DE", "Demerara-Mahaica"),
new State("GY", "EB", "East Berbice-Corentyne"),
new State("GY", "ES", "Essequibo Islands-West Demerara"),
new State("GY", "MA", "Mahaica-Berbice"),
new State("GY", "PM", "Pomeroon-Supenaam"),
new State("GY", "PT", "Potaro-Siparuni"),
new State("GY", "UD", "Upper Demerara-Berbice"),
new State("GY", "UT", "Upper Takutu-Upper Essequibo"),
new State("HN", "AT", "Atlantida"),
new State("HN", "CH", "Choluteca"),
new State("HN", "CL", "Colon"),
new State("HN", "CM", "Comayagua"),
new State("HN", "CP", "Copan"),
new State("HN", "CR", "Cortes"),
new State("HN", "EP", "El Paraiso"),
new State("HN", "FM", "Francisco Morazan"),
new State("HN", "GD", "Gracias a Dios"),
new State("HN", "IN", "Intibuca"),
new State("HN", "IB", "Islas de la Bahia"),
new State("HN", "LP", "La Paz"),
new State("HN", "LE", "Lempira"),
new State("HN", "OC", "Ocotepeque"),
new State("HN", "OL", "Olancho"),
new State("HN", "SB", "Santa Barbara"),
new State("HN", "VA", "Valle"),
new State("HN", "YO", "Yoro"),
new State("HR", "07", "Bjelovarska-Bilogorska"),
new State("HR", "12", "Brodsko-Posavska"),
new State("HR", "19", "Dubrovacko-Neretvanska"),
new State("HR", "18", "Istarska"),
new State("HR", "04", "Karlovacka"),
new State("HR", "06", "Koprivnicko-Krizevacka"),
new State("HR", "02", "Krapinsko-Zagorska"),
new State("HR", "09", "Licko-Senjska"),
new State("HR", "20", "Medimurska"),
new State("HR", "14", "Osjecko-Baranjska"),
new State("HR", "11", "Pozesko-Slavonska"),
new State("HR", "08", "Primorsko-Goranska"),
new State("HR", "15", "Sibensko-Kninska"),
new State("HR", "03", "Sisacko-Moslavacka"),
new State("HR", "17", "Splitsko-Dalmatinska"),
new State("HR", "05", "Varazdinska"),
new State("HR", "10", "Viroviticko-Podravska"),
new State("HR", "16", "Vukovarsko-Srijemska"),
new State("HR", "13", "Zadarska"),
new State("HR", "21", "Zagreb (City)"),
new State("HR", "01", "Zagrebacka"),
new State("HT", "CE", "Centre"),
new State("HT", "GA", "Grand' Anse"),
new State("HT", "AR", "L'Artibonite"),
new State("HT", "NI", "Nippes"),
new State("HT", "ND", "Nord"),
new State("HT", "NE", "Nord-Est"),
new State("HT", "NO", "Nord-Ouest"),
new State("HT", "OU", "Ouest"),
new State("HT", "SD", "Sud"),
new State("HT", "SE", "Sud-Est"),
new State("IE", "CW", "Carlow"),
new State("IE", "CN", "Cavan"),
new State("IE", "CE", "Clare"),
new State("IE", "CO", "Cork"),
new State("IE", "DL", "Donegal"),
new State("IE", "D", "Dublin"),
new State("IE", "G", "Galway"),
new State("IE", "KY", "Kerry"),
new State("IE", "KE", "Kildare"),
new State("IE", "KK", "Kilkenny"),
new State("IE", "LS", "Laois"),
new State("IE", "LM", "Leitrim"),
new State("IE", "LK", "Limerick"),
new State("IE", "LD", "Longford"),
new State("IE", "LH", "Louth"),
new State("IE", "MO", "Mayo"),
new State("IE", "MH", "Meath"),
new State("IE", "MN", "Monaghan"),
new State("IE", "OY", "Offaly"),
new State("IE", "RN", "Roscommon"),
new State("IE", "SO", "Sligo"),
new State("IE", "TA", "Tipperary"),
new State("IE", "WD", "Waterford"),
new State("IE", "WH", "Westmeath"),
new State("IE", "WX", "Wexford"),
new State("IE", "WW", "Wicklow"),
new State("IN", "AN", "Andaman and Nicobar Islands"),
new State("IN", "AP", "Andhra Pradesh"),
new State("IN", "AR", "Arunachal Pradesh"),
new State("IN", "AS", "Assam"),
new State("IN", "BR", "Bihar"),
new State("IN", "CH", "Chandigarh"),
new State("IN", "CG", "Chhattisgarh"),
new State("IN", "DN", "Dadra and Nagar Haveli"),
new State("IN", "DD", "Daman and Diu"),
new State("IN", "DL", "Delhi"),
new State("IN", "GA", "Goa"),
new State("IN", "GJ", "Gujarat"),
new State("IN", "HR", "Haryana"),
new State("IN", "HP", "Himachal Pradesh"),
new State("IN", "JK", "Jammu and Kashmir"),
new State("IN", "JH", "Jharkhand"),
new State("IN", "KA", "Karnataka"),
new State("IN", "KL", "Kerala"),
new State("IN", "LD", "Lakshadweep"),
new State("IN", "MP", "Madhya Pradesh"),
new State("IN", "MH", "Maharashtra"),
new State("IN", "MN", "Manipur"),
new State("IN", "ML", "Meghalaya"),
new State("IN", "MZ", "Mizoram"),
new State("IN", "NL", "Nagaland"),
new State("IN", "OD", "Odisha"),
new State("IN", "PY", "Puducherry"),
new State("IN", "PB", "Punjab"),
new State("IN", "RJ", "Rajasthan"),
new State("IN", "SK", "Sikkim"),
new State("IN", "TN", "Tamil Nadu"),
new State("IN", "TS", "Telangana"),
new State("IN", "TR", "Tripura"),
new State("IN", "UP", "Uttar Pradesh"),
new State("IN", "UK", "Uttarakhand"),
new State("IN", "WB", "West Bengal"),
new State("IS", "1", "Capital"),
new State("IS", "7", "Eastland"),
new State("IS", "6", "Northland East"),
new State("IS", "5", "Northland West"),
new State("IS", "2", "Southern Peninsula"),
new State("IS", "8", "Southland"),
new State("IS", "4", "Western Fjords"),
new State("IS", "3", "Westland"),
new State("IT", "65", "Abruzzo"),
new State("IT", "23", "Aosta Valley"),
new State("IT", "75", "Apulia"),
new State("IT", "77", "Basilicata"),
new State("IT", "78", "Calabria"),
new State("IT", "72", "Campania"),
new State("IT", "45", "Emilia-Romagna"),
new State("IT", "36", "Friuli-Venezia Giulia"),
new State("IT", "62", "Lazio"),
new State("IT", "42", "Liguria"),
new State("IT", "25", "Lombardy"),
new State("IT", "57", "Marche"),
new State("IT", "67", "Molise"),
new State("IT", "21", "Piedmont"),
new State("IT", "88", "Sardinia"),
new State("IT", "82", "Sicily"),
new State("IT", "32", "Trentino-South Tyrol"),
new State("IT", "52", "Tuscany"),
new State("IT", "55", "Umbria"),
new State("IT", "34", "Veneto"),
new State("JP", "23", "Aichi"),
new State("JP", "05", "Akita"),
new State("JP", "02", "Aomori"),
new State("JP", "12", "Chiba"),
new State("JP", "38", "Ehime"),
new State("JP", "18", "Fukui"),
new State("JP", "40", "Fukuoka"),
new State("JP", "07", "Fukushima"),
new State("JP", "21", "Gifu"),
new State("JP", "10", "Gumma"),
new State("JP", "34", "Hiroshima"),
new State("JP", "01", "Hokkaido"),
new State("JP", "28", "Hyogo"),
new State("JP", "08", "Ibaraki"),
new State("JP", "17", "Ishikawa"),
new State("JP", "03", "Iwate"),
new State("JP", "37", "Kagawa"),
new State("JP", "46", "Kagoshima"),
new State("JP", "14", "Kanagawa"),
new State("JP", "39", "Kochi"),
new State("JP", "43", "Kumamoto"),
new State("JP", "26", "Kyoto"),
new State("JP", "24", "Mie"),
new State("JP", "04", "Miyagi"),
new State("JP", "45", "Miyazaki"),
new State("JP", "20", "Nagano"),
new State("JP", "42", "Nagasaki"),
new State("JP", "29", "Nara"),
new State("JP", "15", "Niigata"),
new State("JP", "44", "Oita"),
new State("JP", "33", "Okayama"),
new State("JP", "47", "Okinawa"),
new State("JP", "27", "Osaka"),
new State("JP", "41", "Saga"),
new State("JP", "11", "Saitama"),
new State("JP", "25", "Shiga"),
new State("JP", "32", "Shimane"),
new State("JP", "22", "Shizuoka"),
new State("JP", "09", "Tochigi"),
new State("JP", "36", "Tokushima"),
new State("JP", "13", "Tokyo"),
new State("JP", "31", "Tottori"),
new State("JP", "16", "Toyama"),
new State("JP", "30", "Wakayama"),
new State("JP", "06", "Yamagata"),
new State("JP", "35", "Yamaguchi"),
new State("JP", "19", "Yamanashi"),
new State("KE", "BAR", "Baringo"),
new State("KE", "BOM", "Bomet"),
new State("KE", "BUN", "Bungoma"),
new State("KE", "BUS", "Busia"),
new State("KE", "ELG", "Elgeyo-Marakwet"),
new State("KE", "EMB", "Embu"),
new State("KE", "GAR", "Garissa"),
new State("KE", "HOM", "Homa Bay"),
new State("KE", "ISI", "Isiolo"),
new State("KE", "KAJ", "Kajiado"),
new State("KE", "KAK", "Kakamega"),
new State("KE", "KER", "Kericho"),
new State("KE", "KIA", "Kiambu"),
new State("KE", "KIL", "Kilifi"),
new State("KE", "KIR", "Kirinyaga"),
new State("KE", "KIS", "Kisii"),
new State("KE", "KIM", "Kisumu"),
new State("KE", "KIT", "Kitui"),
new State("KE", "KWA", "Kwale"),
new State("KE", "LAI", "Laikipia"),
new State("KE", "LAM", "Lamu"),
new State("KE", "MAC", "Machakos"),
new State("KE", "MAK", "Makueni"),
new State("KE", "MAN", "Mandera"),
new State("KE", "MAR", "Marsabit"),
new State("KE", "MER", "Meru"),
new State("KE", "MIG", "Migori"),
new State("KE", "MOM", "Mombasa (County)"),
new State("KE", "MUR", "Murang'a"),
new State("KE", "NAI", "Nairobi (County)"),
new State("KE", "NAK", "Nakuru"),
new State("KE", "NAN", "Nandi"),
new State("KE", "NAR", "Narok"),
new State("KE", "NYM", "Nyamira"),
new State("KE", "NYA", "Nyandarua"),
new State("KE", "NYE", "Nyeri"),
new State("KE", "SAM", "Samburu"),
new State("KE", "SIA", "Siaya"),
new State("KE", "TAI", "Taita–Taveta"),
new State("KE", "TAN", "Tana River"),
new State("KE", "THA", "Tharaka-Nithi"),
new State("KE", "TRA", "Trans-Nzoia"),
new State("KE", "TUR", "Turkana"),
new State("KE", "UAS", "Uasin Gishu"),
new State("KE", "VIH", "Vihiga"),
new State("KE", "WAJ", "Wajir"),
new State("KE", "WES", "West Pokot"),
new State("KI", "G", "Gilbert Islands"),
new State("KI", "L", "Line Islands"),
new State("KI", "P", "Phoenix Islands"),
new State("KN", "NE", "Nevis"),
new State("KN", "SK", "Saint Kitts"),
new State("KZ", "AKM", "Akmola"),
new State("KZ", "AKT", "Aktobe"),
new State("KZ", "ALM", "Almaty"),
new State("KZ", "ALC", "Almaty City"),
new State("KZ", "AST", "Astana"),
new State("KZ", "ATY", "Atyrau"),
new State("KZ", "BAI", "Baikonur"),
new State("KZ", "EKZ", "East Kazakhstan"),
new State("KZ", "KAR", "Karagandy"),
new State("KZ", "KOS", "Kostanay"),
new State("KZ", "KYZ", "Kyzylorda"),
new State("KZ", "MAN", "Mangystau"),
new State("KZ", "NKZ", "North Kazakhstan"),
new State("KZ", "PAV", "Pavlodar"),
new State("KZ", "SHY", "Shymkent"),
new State("KZ", "TUR", "Turkistan"),
new State("KZ", "WKZ", "West Kazakhstan"),
new State("KZ", "ZHA", "Zhambyl"),
new State("LC", "01", "Anse-la-Raye"),
new State("LC", "12", "Canaries"),
new State("LC", "02", "Castries"),
new State("LC", "03", "Choiseul"),
new State("LC", "05", "Dennery"),
new State("LC", "06", "Gros Islet"),
new State("LC", "07", "Laborie"),
new State("LC", "08", "Micoud"),
new State("LC", "10", "Soufrière"),
new State("LC", "11", "Vieux Fort"),
new State("LI", "BA", "Balzers"),
new State("LI", "ES", "Eschen"),
new State("LI", "GA", "Gamprin"),
new State("LI", "MA", "Mauren"),
new State("LI", "PL", "Planken"),
new State("LI", "RU", "Ruggel"),
new State("LI", "SN", "Schaan"),
new State("LI", "SB", "Schellenberg"),
new State("LI", "TN", "Triesen"),
new State("LI", "TB", "Triesenberg"),
new State("LI", "VA", "Vaduz"),
new State("LS", "D", "Berea"),
new State("LS", "B", "Butha-Buthe"),
new State("LS", "C", "Leribe"),
new State("LS", "E", "Mafeteng"),
new State("LS", "A", "Maseru"),
new State("LS", "F", "Mohale's Hoek"),
new State("LS", "J", "Mokhotlong"),
new State("LS", "H", "Qacha's Nek"),
new State("LS", "G", "Quthing"),
new State("LS", "K", "Thaba-Tseka"),
new State("LU", "D", "Diekirch"),
new State("LU", "G", "Grevenmacher"),
new State("LU", "L", "Luxembourg"),
new State("LV", "011", "Adazi"),
new State("LV", "001", "Aglona"),
new State("LV", "002", "Aizkraukle"),
new State("LV", "003", "Aizpute"),
new State("LV", "004", "Akniste"),
new State("LV", "005", "Aloja"),
new State("LV", "006", "Alsunga"),
new State("LV", "007", "Aluksne"),
new State("LV", "008", "Amata"),
new State("LV", "009", "Ape"),
new State("LV", "010", "Auce"),
new State("LV", "012", "Babite"),
new State("LV", "013", "Baldone"),
new State("LV", "014", "Baltinava"),
new State("LV", "015", "Balvi"),
new State("LV", "016", "Bauska"),
new State("LV", "017", "Beverina"),
new State("LV", "018", "Broceni"),
new State("LV", "019", "Burtnieki"),
new State("LV", "020", "Carnikava"),
new State("LV", "022", "Cesis"),
new State("LV", "021", "Cesvaine"),
new State("LV", "023", "Cibla"),
new State("LV", "024", "Dagda"),
new State("LV", "025", "Daugavpils"),
new State("LV", "DGV", "Daugavpils"),
new State("LV", "026", "Dobele"),
new State("LV", "027", "Dundaga"),
new State("LV", "028", "Durbe"),
new State("LV", "029", "Engure"),
new State("LV", "030", "Ergli"),
new State("LV", "031", "Garkalne"),
new State("LV", "032", "Grobina"),
new State("LV", "033", "Gulbene"),
new State("LV", "034", "Iecava"),
new State("LV", "035", "Ikskile"),
new State("LV", "036", "Ilukste"),
new State("LV", "037", "Incukalns"),
new State("LV", "038", "Jaunjelgava"),
new State("LV", "039", "Jaunpiebalga"),
new State("LV", "040", "Jaunpils"),
new State("LV", "042", "Jekabpils"),
new State("LV", "JKB", "Jekabpils"),
new State("LV", "JEL", "Jelgava"),
new State("LV", "041", "Jelgava"),
new State("LV", "JUR", "Jurmala"),
new State("LV", "043", "Kandava"),
new State("LV", "044", "Karsava"),
new State("LV", "051", "Kegums"),
new State("LV", "052", "Kekava"),
new State("LV", "045", "Kocenu"),
new State("LV", "046", "Koknese"),
new State("LV", "047", "Kraslava"),
new State("LV", "048", "Krimulda"),
new State("LV", "049", "Krustpils"),
new State("LV", "050", "Kuldiga"),
new State("LV", "053", "Lielvarde"),
new State("LV", "LPX", "Liepaja"),
new State("LV", "055", "Ligatne"),
new State("LV", "054", "Limbazi"),
new State("LV", "056", "Livani"),
new State("LV", "057", "Lubana"),
new State("LV", "058", "Ludza"),
new State("LV", "059", "Madona"),
new State("LV", "061", "Malpils"),
new State("LV", "062", "Marupe"),
new State("LV", "060", "Mazsalaca"),
new State("LV", "063", "Mersraga"),
new State("LV", "064", "Naukseni"),
new State("LV", "065", "Nereta"),
new State("LV", "066", "Nica"),
new State("LV", "067", "Ogre"),
new State("LV", "068", "Olaine"),
new State("LV", "069", "Ozolnieki"),
new State("LV", "070", "Pargauja"),
new State("LV", "071", "Pavilosta"),
new State("LV", "072", "Plavinas"),
new State("LV", "073", "Preili"),
new State("LV", "074", "Priekule"),
new State("LV", "075", "Priekuli"),
new State("LV", "076", "Rauna"),
new State("LV", "077", "Rezekne"),
new State("LV", "REZ", "Rezekne"),
new State("LV", "078", "Riebini"),
new State("LV", "RIX", "Riga"),
new State("LV", "079", "Roja"),
new State("LV", "080", "Ropazi"),
new State("LV", "081", "Rucava"),
new State("LV", "082", "Rugaji"),
new State("LV", "084", "Rujiena"),
new State("LV", "083", "Rundale"),
new State("LV", "085", "Sala"),
new State("LV", "086", "Salacgriva"),
new State("LV", "087", "Salaspils"),
new State("LV", "088", "Saldus"),
new State("LV", "089", "Saulkrasti"),
new State("LV", "090", "Seja"),
new State("LV", "091", "Sigulda"),
new State("LV", "092", "Skriveri"),
new State("LV", "093", "Skrunda"),
new State("LV", "094", "Smiltene"),
new State("LV", "095", "Stopini"),
new State("LV", "096", "Strenci"),
new State("LV", "097", "Talsi"),
new State("LV", "098", "Tervete"),
new State("LV", "099", "Tukums"),
new State("LV", "100", "Vainode"),
new State("LV", "101", "Valka"),
new State("LV", "VMR", "Valmiera"),
new State("LV", "102", "Varaklani"),
new State("LV", "103", "Varkava"),
new State("LV", "104", "Vecpiebalga"),
new State("LV", "105", "Vecumnieki"),
new State("LV", "106", "Ventspils"),
new State("LV", "VEN", "Ventspils"),
new State("LV", "107", "Viesite"),
new State("LV", "108", "Vilaka"),
new State("LV", "109", "Vilani"),
new State("LV", "110", "Zilupe"),
new State("MA", "BK", "Beni Mellal-Khenifra"),
new State("MA", "CS", "Casablanca-Settat"),
new State("MA", "OL", "Dakhla-Oued Ed-Dahab"),
new State("MA", "DT", "Draa-Tafilalet"),
new State("MA", "FK", "Fes-Meknes"),
new State("MA", "GN", "Guelmim-Oued Noun"),
new State("MA", "LS", "Laayoune-Sakia al Hamra"),
new State("MA", "OF", "L'oriental"),
new State("MA", "MS", "Marrakech-Safi"),
new State("MA", "RK", "Rabat-Sale-Kenitra"),
new State("MA", "SS", "Souss-Massa"),
new State("MA", "TC", "Tanger-Tetouan-Al Hoceima"),
new State("MG", "ALM", "Alaotra-Mangoro"),
new State("MG", "AMO", "Amoron'i Mania"),
new State("MG", "ANA", "Analamanga"),
new State("MG", "ANJ", "Analanjirofo"),
new State("MG", "AND", "Androy"),
new State("MG", "ANO", "Anosy"),
new State("MG", "AAF", "Atsimo-Andrefana"),
new State("MG", "ATT", "Atsimo-Atsinanana"),
new State("MG", "ATS", "Atsinanana"),
new State("MG", "BET", "Betsiboka"),
new State("MG", "BOE", "Boeny"),
new State("MG", "BON", "Bongolava"),
new State("MG", "DIA", "Diana"),
new State("MG", "IHO", "Ihorombe"),
new State("MG", "ITA", "Itasy"),
new State("MG", "MAT", "Matsiatra Ambony"),
new State("MG", "MEL", "Melaky"),
new State("MG", "MEN", "Menabe"),
new State("MG", "SAV", "Sava"),
new State("MG", "SOF", "Sofia"),
new State("MG", "VAK", "Vakinankaratra"),
new State("MG", "VAT", "Vatovavy-Fitovinany"),
new State("MH", "ALL", "Ailinglaplap"),
new State("MH", "ALK", "Ailuk"),
new State("MH", "ARN", "Arno"),
new State("MH", "AUR", "Aur"),
new State("MH", "KIL", "Bikini & Kili"),
new State("MH", "EBO", "Ebon"),
new State("MH", "ENI", "Enewetak & Ujelang"),
new State("MH", "JAB", "Jabat"),
new State("MH", "JAL", "Jaluit"),
new State("MH", "KWA", "Kwajalein"),
new State("MH", "LAE", "Lae"),
new State("MH", "LIB", "Lib"),
new State("MH", "LIK", "Likiep"),
new State("MH", "MAJ", "Majuro"),
new State("MH", "MAL", "Maloelap"),
new State("MH", "MEJ", "Mejit"),
new State("MH", "MIL", "Mili"),
new State("MH", "NMK", "Namdrik"),
new State("MH", "NMU", "Namu"),
new State("MH", "RON", "Rongelap"),
new State("MH", "UJA", "Ujae"),
new State("MH", "UTI", "Utrik"),
new State("MH", "WTH", "Wotho"),
new State("MH", "WTJ", "Wotje"),
new State("MU", "AG", "Agalega Islands"),
new State("MU", "BL", "Black River"),
new State("MU", "CC", "Cargados Carajos"),
new State("MU", "FL", "Flacq"),
new State("MU", "GP", "Grand Port"),
new State("MU", "MP", "Moka"),
new State("MU", "PA", "Pamplemousses"),
new State("MU", "PW", "Plaines Wilhems"),
new State("MU", "PL", "Port Louis"),
new State("MU", "RR", "Rivière du Rempart"),
new State("MU", "RO", "Rodrigues"),
new State("MU", "SA", "Savanne"),
new State("MV", "02", "Alifu Alifu"),
new State("MV", "00", "Alifu Dhaalu"),
new State("MV", "20", "Baa"),
new State("MV", "17", "Dhaalu"),
new State("MV", "14", "Faafu"),
new State("MV", "27", "Gaafu Alifu"),
new State("MV", "28", "Gaafu Dhaalu"),
new State("MV", "29", "Gnaviyani"),
new State("MV", "07", "Haa Alifu"),
new State("MV", "23", "Haa Dhaalu"),
new State("MV", "26", "Kaafu"),
new State("MV", "05", "Laamu"),
new State("MV", "03", "Lhaviyani"),
new State("MV", "MA", "Maale Capital"),
new State("MV", "12", "Meemu"),
new State("MV", "25", "Noonu"),
new State("MV", "13", "Raa"),
new State("MV", "01", "Seenu"),
new State("MV", "24", "Shaviyani"),
new State("MV", "08", "Thaa"),
new State("MV", "04", "Vaavu"),
new State("MW", "BA", "Balaka"),
new State("MW", "BL", "Blantyre"),
new State("MW", "CK", "Chikwawa"),
new State("MW", "CR", "Chiradzulu"),
new State("MW", "CT", "Chitipa"),
new State("MW", "DE", "Dedza"),
new State("MW", "DO", "Dowa"),
new State("MW", "KR", "Karonga"),
new State("MW", "KS", "Kasungu"),
new State("MW", "LK", "Likoma"),
new State("MW", "LI", "Lilongwe"),
new State("MW", "MH", "Machinga"),
new State("MW", "MG", "Mangochi"),
new State("MW", "MC", "Mchinji"),
new State("MW", "MU", "Mulanje"),
new State("MW", "MW", "Mwanza"),
new State("MW", "MZ", "Mzimba"),
new State("MW", "NE", "Neno"),
new State("MW", "NB", "Nkhata Bay"),
new State("MW", "NK", "Nkhotakota"),
new State("MW", "NS", "Nsanje"),
new State("MW", "NU", "Ntcheu"),
new State("MW", "NI", "Ntchisi"),
new State("MW", "PH", "Phalombe"),
new State("MW", "RU", "Rumphi"),
new State("MW", "SA", "Salima"),
new State("MW", "TH", "Thyolo"),
new State("MW", "ZO", "Zomba"),
new State("MX", "AGS", "Aguascalientes"),
new State("MX", "BC", "Baja California"),
new State("MX", "BCS", "Baja California Sur"),
new State("MX", "CAM", "Campeche"),
new State("MX", "CHS", "Chiapas"),
new State("MX", "CHH", "Chihuahua"),
new State("MX", "COA", "Coahuila"),
new State("MX", "COL", "Colima"),
new State("MX", "DUR", "Durango"),
new State("MX", "GTO", "Guanajuato"),
new State("MX", "GRO", "Guerrero"),
new State("MX", "HDG", "Hidalgo"),
new State("MX", "JAL", "Jalisco"),
new State("MX", "CDM", "Mexico City"),
new State("MX", "MIC", "Michoacan"),
new State("MX", "MOR", "Morelos"),
new State("MX", "NAY", "Nayarit"),
new State("MX", "NL", "Nuevo Leon"),
new State("MX", "OAX", "Oaxaca"),
new State("MX", "PUE", "Puebla"),
new State("MX", "QRO", "Queretaro"),
new State("MX", "QR", "Quintana Roo"),
new State("MX", "SLP", "San Luis Potosi"),
new State("MX", "SNL", "Sinaloa"),
new State("MX", "SON", "Sonora"),
new State("MX", "EM", "State of Mexico"),
new State("MX", "TAB", "Tabasco"),
new State("MX", "TAM", "Tamaulipas"),
new State("MX", "TLA", "Tlaxcala"),
new State("MX", "VER", "Veracruz"),
new State("MX", "YUC", "Yucatan"),
new State("MX", "ZAC", "Zacatecas"),
new State("MZ", "CD", "Cabo Delgado"),
new State("MZ", "GA", "Gaza"),
new State("MZ", "IN", "Inhambane"),
new State("MZ", "MA", "Manica"),
new State("MZ", "MP", "Maputo"),
new State("MZ", "MC", "Maputo City"),
new State("MZ", "NA", "Nampula"),
new State("MZ", "NI", "Niassa"),
new State("MZ", "SO", "Sofala"),
new State("MZ", "TE", "Tete"),
new State("MZ", "ZA", "Zambezia"),
new State("NA", "ER", "Erongo"),
new State("NA", "HA", "Hardap"),
new State("NA", "KA", "Karas"),
new State("NA", "KE", "Kavango East"),
new State("NA", "KW", "Kavango West"),
new State("NA", "KH", "Khomas"),
new State("NA", "KU", "Kunene"),
new State("NA", "OH", "Ohangwena"),
new State("NA", "OK", "Omaheke"),
new State("NA", "OM", "Omusati"),
new State("NA", "OA", "Oshana"),
new State("NA", "OO", "Oshikoto"),
new State("NA", "OT", "Otjozondjupa"),
new State("NA", "ZA", "Zambezi"),
new State("NI", "BO", "Boaco"),
new State("NI", "CA", "Carazo"),
new State("NI", "CI", "Chinandega"),
new State("NI", "CO", "Chontales"),
new State("NI", "AN", "Costa Caribe Norte"),
new State("NI", "AS", "Costa Caribe Sur"),
new State("NI", "ES", "Esteli"),
new State("NI", "GR", "Granada"),
new State("NI", "JI", "Jinotega"),
new State("NI", "LE", "Leon"),
new State("NI", "MD", "Madriz"),
new State("NI", "MN", "Managua"),
new State("NI", "MS", "Masaya"),
new State("NI", "MT", "Matagalpa"),
new State("NI", "NS", "Nueva Segovia"),
new State("NI", "SJ", "Rio San Juan"),
new State("NI", "RI", "Rivas"),
new State("NL", "DR", "Drenthe"),
new State("NL", "FL", "Flevoland"),
new State("NL", "FR", "Friesland"),
new State("NL", "GE", "Gelderland"),
new State("NL", "GR", "Groningen"),
new State("NL", "LI", "Limburg"),
new State("NL", "NB", "Noord-Brabant"),
new State("NL", "NH", "Noord-Holland"),
new State("NL", "OV", "Overijssel"),
new State("NL", "UT", "Utrecht"),
new State("NL", "ZE", "Zeeland"),
new State("NL", "ZH", "Zuid-Holland"),
new State("NO", "20", "Finnmark"),
new State("NO", "04", "Hedmark"),
new State("NO", "12", "Hordaland"),
new State("NO", "15", "More og Romsdal"),
new State("NO", "18", "Nordland"),
new State("NO", "17", "Nord-Trondelag"),
new State("NO", "05", "Oppland"),
new State("NO", "03", "Oslo"),
new State("NO", "01", "Ostfold"),
new State("NO", "11", "Rogaland"),
new State("NO", "14", "Sogn og Fjordane"),
new State("NO", "16", "Sor-Trondelag"),
new State("NO", "08", "Telemark"),
new State("NO", "19", "Troms"),
new State("NO", "10", "Vest-Agder"),
new State("NO", "07", "Vestfold"),
new State("NR", "01", "Aiwo"),
new State("NR", "02", "Anabar"),
new State("NR", "03", "Anetan"),
new State("NR", "04", "Anibare"),
new State("NR", "05", "Baitsi"),
new State("NR", "06", "Boe"),
new State("NR", "07", "Buada"),
new State("NR", "08", "Denigomodu"),
new State("NR", "09", "Ewa"),
new State("NR", "10", "Ijuw"),
new State("NR", "11", "Meneng"),
new State("NR", "12", "Nibok"),
new State("NR", "13", "Uaboe"),
new State("NR", "14", "Yaren"),
new State("NZ", "AUK", "Auckland"),
new State("NZ", "BOP", "Bay of Plenty"),
new State("NZ", "CAN", "Canterbury"),
new State("NZ", "CIT", "Chatham Islands Territory"),
new State("NZ", "GIS", "Gisborne"),
new State("NZ", "HKB", "Hawke's Bay"),
new State("NZ", "MWT", "Manawatu-Wanganui"),
new State("NZ", "MBH", "Marlborough"),
new State("NZ", "NSN", "Nelson"),
new State("NZ", "NTL", "Northland"),
new State("NZ", "OTA", "Otago"),
new State("NZ", "STL", "Southland"),
new State("NZ", "TKI", "Taranaki"),
new State("NZ", "TAS", "Tasman"),
new State("NZ", "WKO", "Waikato"),
new State("NZ", "WGN", "Wellington"),
new State("NZ", "WTC", "West Coast"),
new State("PA", "1", "Bocas del Toro"),
new State("PA", "4", "Chiriqui"),
new State("PA", "2", "Cocle"),
new State("PA", "3", "Colon"),
new State("PA", "5", "Darien"),
new State("PA", "EM", "Embera"),
new State("PA", "6", "Herrera"),
new State("PA", "KY", "Kuna Yala"),
new State("PA", "7", "Los Santos"),
new State("PA", "NB", "Ngabe Bugle"),
new State("PA", "8", "Panama"),
new State("PA", "10", "Panama Oeste"),
new State("PA", "9", "Veraguas"),
new State("PE", "AMA", "Amazonas"),
new State("PE", "ANC", "Ancash"),
new State("PE", "APU", "Apurimac"),
new State("PE", "ARE", "Arequipa"),
new State("PE", "AYA", "Ayacucho"),
new State("PE", "CAJ", "Cajamarca"),
new State("PE", "CAL", "Callao"),
new State("PE", "CUS", "Cusco"),
new State("PE", "HUV", "Huancavelica"),
new State("PE", "HUC", "Huanuco"),
new State("PE", "ICA", "Ica"),
new State("PE", "JUN", "Junin"),
new State("PE", "LAL", "La Libertad"),
new State("PE", "LAM", "Lambayeque"),
new State("PE", "LIM", "Lima"),
new State("PE", "LOR", "Loreto"),
new State("PE", "MDD", "Madre de Dios"),
new State("PE", "MOQ", "Moquegua"),
new State("PE", "PAS", "Pasco"),
new State("PE", "PIU", "Piura"),
new State("PE", "PUN", "Puno"),
new State("PE", "SAM", "San Martin"),
new State("PE", "TAC", "Tacna"),
new State("PE", "TUM", "Tumbes"),
new State("PE", "UCA", "Ucayali"),
new State("PG", "NSB", "Bougainville"),
new State("PG", "CPM", "Central"),
new State("PG", "EBR", "East New Britain"),
new State("PG", "ESW", "East Sepik"),
new State("PG", "EHG", "Eastern Highlands"),
new State("PG", "EPW", "Enga"),
new State("PG", "GPK", "Gulf"),
new State("PG", "HEL", "Hela"),
new State("PG", "JWK", "Jiwaka"),
new State("PG", "MPM", "Madang"),
new State("PG", "MRL", "Manus"),
new State("PG", "MBA", "Milne Bay"),
new State("PG", "MPL", "Morobe"),
new State("PG", "NCD", "National Capital District"),
new State("PG", "NIK", "New Ireland"),
new State("PG", "NPP", "Oro (Northern)"),
new State("PG", "SAN", "Sandaun (West Sepik)"),
new State("PG", "CPK", "Simbu (Chimbu)"),
new State("PG", "SHM", "Southern Highlands"),
new State("PG", "WBK", "West New Britain"),
new State("PG", "WPD", "Western (Fly)"),
new State("PG", "WHM", "Western Highlands"),
new State("PH", "ABR", "Abra"),
new State("PH", "AGN", "Agusan del Norte"),
new State("PH", "AGS", "Agusan del Sur"),
new State("PH", "AKL", "Aklan"),
new State("PH", "ALB", "Albay"),
new State("PH", "ANT", "Antique"),
new State("PH", "APA", "Apayao"),
new State("PH", "AUR", "Aurora"),
new State("PH", "BAS", "Basilan"),
new State("PH", "BAN", "Bataan"),
new State("PH", "BTN", "Batanes"),
new State("PH", "BTG", "Batangas"),
new State("PH", "BEN", "Benguet"),
new State("PH", "BIL", "Biliran"),
new State("PH", "BOH", "Bohol"),
new State("PH", "BUK", "Bukidnon"),
new State("PH", "BUL", "Bulacan"),
new State("PH", "CAG", "Cagayan"),
new State("PH", "CAN", "Camarines Norte"),
new State("PH", "CAS", "Camarines Sur"),
new State("PH", "CAM", "Camiguin"),
new State("PH", "CAP", "Capiz"),
new State("PH", "CAT", "Catanduanes"),
new State("PH", "CAV", "Cavite"),
new State("PH", "CEB", "Cebu"),
new State("PH", "COM", "Compostela Valley"),
new State("PH", "NCO", "Cotabato"),
new State("PH", "DAV", "Davao del Norte"),
new State("PH", "DAS", "Davao del Sur"),
new State("PH", "DVO", "Davao Occidental"),
new State("PH", "DAO", "Davao Oriental"),
new State("PH", "DIN", "Dinagat Islands"),
new State("PH", "EAS", "Eastern Samar"),
new State("PH", "GUI", "Guimaras"),
new State("PH", "IFU", "Ifugao"),
new State("PH", "ILN", "Ilocos Norte"),
new State("PH", "ILS", "Ilocos Sur"),
new State("PH", "ILI", "Iloilo"),
new State("PH", "ISA", "Isabela"),
new State("PH", "KAL", "Kalinga"),
new State("PH", "LUN", "La Union"),
new State("PH", "LAG", "Laguna"),
new State("PH", "LAN", "Lanao del Norte"),
new State("PH", "LAS", "Lanao del Sur"),
new State("PH", "LEY", "Leyte"),
new State("PH", "MAG", "Maguindanao"),
new State("PH", "MNL", "Manila, Metropolitan"),
new State("PH", "MAD", "Marinduque"),
new State("PH", "MAS", "Masbate"),
new State("PH", "MSC", "Misamis Occidental"),
new State("PH", "MSR", "Misamis Oriental"),
new State("PH", "MOU", "Mountain"),
new State("PH", "NEC", "Negros Occidental"),
new State("PH", "NER", "Negros Oriental"),
new State("PH", "NSA", "Northern Samar"),
new State("PH", "NUE", "Nueva Ecija"),
new State("PH", "NUV", "Nueva Vizcaya"),
new State("PH", "MDC", "Occidental Mindoro"),
new State("PH", "MDR", "Oriental Mindoro"),
new State("PH", "PLW", "Palawan"),
new State("PH", "PAM", "Pampanga"),
new State("PH", "PAN", "Pangasinan"),
new State("PH", "QUE", "Quezon"),
new State("PH", "QUI", "Quirino"),
new State("PH", "RIZ", "Rizal"),
new State("PH", "ROM", "Romblon"),
new State("PH", "WSA", "Samar"),
new State("PH", "SAR", "Sarangani"),
new State("PH", "SIG", "Siquijor"),
new State("PH", "SOR", "Sorsogon"),
new State("PH", "SCO", "South Cotabato"),
new State("PH", "SLE", "Southern Leyte"),
new State("PH", "SUK", "Sultan Kudarat"),
new State("PH", "SLU", "Sulu"),
new State("PH", "SUN", "Surigao del Norte"),
new State("PH", "SUR", "Surigao del Sur"),
new State("PH", "TAR", "Tarlac"),
new State("PH", "TAW", "Tawi-Tawi"),
new State("PH", "ZMB", "Zambales"),
new State("PH", "ZAN", "Zamboanga del Norte"),
new State("PH", "ZAS", "Zamboanga del Sur"),
new State("PH", "ZSI", "Zamboanga-Sibugay"),
new State("PL", "WP", "Greater Poland"),
new State("PL", "SK", "Holy Cross"),
new State("PL", "KP", "Kuyavia-Pomerania"),
new State("PL", "MA", "Lesser Poland"),
new State("PL", "LD", "Lodz"),
new State("PL", "DS", "Lower Silesia"),
new State("PL", "LU", "Lublin"),
new State("PL", "LB", "Lubusz"),
new State("PL", "MZ", "Mazovia"),
new State("PL", "OP", "Opole (Upper Silesia)"),
new State("PL", "PD", "Podlaskie"),
new State("PL", "PM", "Pomerania"),
new State("PL", "SL", "Silesia"),
new State("PL", "PK", "Subcarpathia"),
new State("PL", "WN", "Warmia-Masuria"),
new State("PL", "ZP", "Western Pomerania"),
new State("PT", "01", "Aveiro"),
new State("PT", "20", "Azores"),
new State("PT", "02", "Beja"),
new State("PT", "03", "Braga"),
new State("PT", "04", "Braganca"),
new State("PT", "05", "Castelo Branco"),
new State("PT", "06", "Coimbra"),
new State("PT", "07", "Evora"),
new State("PT", "08", "Faro"),
new State("PT", "09", "Guarda"),
new State("PT", "10", "Leiria"),
new State("PT", "11", "Lisboa"),
new State("PT", "30", "Madeira"),
new State("PT", "12", "Portalegre"),
new State("PT", "13", "Porto"),
new State("PT", "14", "Santarem"),
new State("PT", "15", "Setubal"),
new State("PT", "16", "Viana do Castelo"),
new State("PT", "17", "Vila Real"),
new State("PT", "18", "Viseu"),
new State("PW", "002", "Aimeliik"),
new State("PW", "004", "Airai"),
new State("PW", "010", "Angaur"),
new State("PW", "050", "Hatohobei"),
new State("PW", "100", "Kayangel"),
new State("PW", "150", "Koror"),
new State("PW", "212", "Melekeok"),
new State("PW", "214", "Ngaraard"),
new State("PW", "218", "Ngarchelong"),
new State("PW", "222", "Ngardmau"),
new State("PW", "224", "Ngatpang"),
new State("PW", "226", "Ngchesar"),
new State("PW", "227", "Ngeremlengui"),
new State("PW", "228", "Ngiwal"),
new State("PW", "350", "Peleliu"),
new State("PW", "370", "Sonsorol "),
new State("PY", "16", "Alto Paraguay"),
new State("PY", "10", "Alto Parana"),
new State("PY", "13", "Amambay"),
new State("PY", "17", "Boqueron"),
new State("PY", "5", "Caaguazu"),
new State("PY", "6", "Caazapa"),
new State("PY", "14", "Canindeyu"),
new State("PY", "ASU", "Capital District"),
new State("PY", "11", "Central"),
new State("PY", "1", "Concepcion"),
new State("PY", "3", "Cordillera"),
new State("PY", "4", "Guaira"),
new State("PY", "7", "Itapua"),
new State("PY", "8", "Misiones"),
new State("PY", "12", "Neembucu"),
new State("PY", "9", "Paraguari"),
new State("PY", "15", "Presidente Hayes"),
new State("PY", "2", "San Pedro"),
new State("QA", "DA", "Ad Dawhah"),
new State("QA", "ZA", "Al Daayen"),
new State("QA", "KH", "Al Khawr"),
new State("QA", "WA", "Al Wakrah"),
new State("QA", "RA", "Ar Rayyan"),
new State("QA", "MS", "Madinat ach Shamal"),
new State("QA", "US", "Umm Salal"),
new State("RU", "01", "Adygea"),
new State("RU", "22", "Altai Krai"),
new State("RU", "04", "Altai Republic"),
new State("RU", "28", "Amur Oblast"),
new State("RU", "29", "Arkhangelsk Oblast"),
new State("RU", "30", "Astrakhan Oblast"),
new State("RU", "02", "Bashkortostan"),
new State("RU", "31", "Belgorod Oblast"),
new State("RU", "32", "Bryansk Oblast"),
new State("RU", "03", "Buryatia"),
new State("RU", "20", "Chechen Republic"),
new State("RU", "74", "Chelyabinsk Oblast"),
new State("RU", "87", "Chukotka Autonomous Okrug"),
new State("RU", "21", "Chuvash Republic"),
new State("RU", "82", "Crimea"),
new State("RU", "05", "Dagestan"),
new State("RU", "06", "Ingushetia"),
new State("RU", "38", "Irkutsk Oblast"),
new State("RU", "37", "Ivanovo Oblast"),
new State("RU", "79", "Jewish Autonomous Oblast"),
new State("RU", "07", "Kabardino-Balkar Republic"),
new State("RU", "39", "Kaliningrad Oblast"),
new State("RU", "08", "Kalmykia"),
new State("RU", "40", "Kaluga Oblast"),
new State("RU", "41", "Kamchatka Krai"),
new State("RU", "09", "Karachay-Cherkess Republic"),
new State("RU", "10", "Karelia"),
new State("RU", "42", "Kemerovo Oblast"),
new State("RU", "27", "Khabarovsk Krai"),
new State("RU", "19", "Khakassia"),
new State("RU", "86", "Khanty–Mansi Autonomous Okrug – Yugra"),
new State("RU", "43", "Kirov Oblast"),
new State("RU", "11", "Komi Republic"),
new State("RU", "44", "Kostroma Oblast"),
new State("RU", "23", "Krasnodar Krai"),
new State("RU", "24", "Krasnoyarsk Krai"),
new State("RU", "45", "Kurgan Oblast"),
new State("RU", "46", "Kursk Oblast"),
new State("RU", "47", "Leningrad Oblast"),
new State("RU", "48", "Lipetsk Oblast"),
new State("RU", "49", "Magadan Oblast"),
new State("RU", "12", "Mari El Republic"),
new State("RU", "13", "Mordovia"),
new State("RU", "77", "Moscow"),
new State("RU", "50", "Moscow Oblast"),
new State("RU", "51", "Murmansk Oblast"),
new State("RU", "83", "Nenets Autonomous Okrug"),
new State("RU", "52", "Nizhny Novgorod Oblast"),
new State("RU", "15", "North Ossetia-Alania"),
new State("RU", "53", "Novgorod Oblast"),
new State("RU", "54", "Novosibirsk Oblast"),
new State("RU", "55", "Omsk Oblast"),
new State("RU", "56", "Orenburg Oblast"),
new State("RU", "57", "Oryol Oblast"),
new State("RU", "58", "Penza Oblast"),
new State("RU", "59", "Perm Krai"),
new State("RU", "25", "Primorsky Krai"),
new State("RU", "60", "Pskov Oblast"),
new State("RU", "61", "Rostov Oblast"),
new State("RU", "62", "Ryazan Oblast"),
new State("RU", "78", "Saint Petersburg"),
new State("RU", "14", "Sakha (Yakutia) Republic"),
new State("RU", "65", "Sakhalin Oblast"),
new State("RU", "63", "Samara Oblast"),
new State("RU", "64", "Saratov Oblast"),
new State("RU", "92", "Sevastopol"),
new State("RU", "67", "Smolensk Oblast"),
new State("RU", "26", "Stavropol Krai"),
new State("RU", "66", "Sverdlovsk Oblast"),
new State("RU", "68", "Tambov Oblast"),
new State("RU", "16", "Tatarstan"),
new State("RU", "70", "Tomsk Oblast"),
new State("RU", "71", "Tula Oblast"),
new State("RU", "17", "Tuva Republic"),
new State("RU", "69", "Tver Oblast"),
new State("RU", "72", "Tyumen Oblast"),
new State("RU", "18", "Udmurt Republic"),
new State("RU", "73", "Ulyanovsk Oblast"),
new State("RU", "33", "Vladimir Oblast"),
new State("RU", "34", "Volgograd Oblast"),
new State("RU", "35", "Vologda Oblast"),
new State("RU", "36", "Voronezh Oblast"),
new State("RU", "89", "Yamalo-Nenets Autonomous Okrug"),
new State("RU", "76", "Yaroslavl Oblast"),
new State("RU", "75", "Zabaykalsky Krai"),
new State("SB", "CT", "Capital Territory"),
new State("SB", "CE", "Central"),
new State("SB", "CH", "Choiseul"),
new State("SB", "GU", "Guadalcanal"),
new State("SB", "IS", "Isabel"),
new State("SB", "MK", "Makira-Ulawa"),
new State("SB", "ML", "Malaita"),
new State("SB", "RB", "Rennell and Bellona"),
new State("SB", "TE", "Temotu"),
new State("SB", "WE", "Western"),
new State("SE", "K", "Blekinge"),
new State("SE", "W", "Dalarna"),
new State("SE", "X", "Gavleborg"),
new State("SE", "I", "Gotland"),
new State("SE", "N", "Halland"),
new State("SE", "Z", "Jamtland"),
new State("SE", "F", "Jonkoping"),
new State("SE", "H", "Kalmar"),
new State("SE", "G", "Kronoberg"),
new State("SE", "BD", "Norrbotten"),
new State("SE", "T", "Orebro"),
new State("SE", "E", "Ostergotland"),
new State("SE", "M", "Skane"),
new State("SE", "D", "Sodermanland"),
new State("SE", "AB", "Stockholm"),
new State("SE", "C", "Uppsala"),
new State("SE", "S", "Varmland"),
new State("SE", "AC", "Vasterbotten"),
new State("SE", "Y", "Vasternorrland"),
new State("SE", "U", "Vastmanland"),
new State("SE", "O", "Vastra Gotaland"),
new State("SG", "01", "Central"),
new State("SG", "02", "North East"),
new State("SG", "03", "North West"),
new State("SG", "04", "South East"),
new State("SG", "05", "South West"),
new State("SM", "01", "Acquaviva"),
new State("SM", "06", "Borgo Maggiore"),
new State("SM", "02", "Chiesanuova"),
new State("SM", "03", "Domagnano"),
new State("SM", "04", "Faetano"),
new State("SM", "05", "Fiorentino"),
new State("SM", "08", "Montegiardino"),
new State("SM", "07", "San Marino"),
new State("SM", "09", "Serravalle"),
new State("SN", "DK", "Dakar"),
new State("SN", "DB", "Diourbel"),
new State("SN", "FK", "Fatick"),
new State("SN", "KA", "Kaffrine"),
new State("SN", "KL", "Kaolack"),
new State("SN", "KE", "Kedougou"),
new State("SN", "KD", "Kolda"),
new State("SN", "LG", "Louga"),
new State("SN", "MT", "Matam"),
new State("SN", "SL", "Saint-Louis"),
new State("SN", "SE", "Sedhiou"),
new State("SN", "TC", "Tambacounda"),
new State("SN", "TH", "Thies"),
new State("SN", "ZG", "Ziguinchor"),
new State("SR", "BR", "Brokopondo"),
new State("SR", "CM", "Commewijne"),
new State("SR", "CO", "Coronie"),
new State("SR", "MA", "Marowijne"),
new State("SR", "NI", "Nickerie"),
new State("SR", "PA", "Para"),
new State("SR", "PM", "Paramaribo"),
new State("SR", "SA", "Saramacca"),
new State("SR", "SI", "Sipaliwini"),
new State("SR", "WA", "Wanica"),
new State("SV", "AH", "Ahuachapan "),
new State("SV", "CA", "Cabanas "),
new State("SV", "CH", "Chalatenango"),
new State("SV", "CU", "Cuscatlan "),
new State("SV", "LI", "La Libertad "),
new State("SV", "PA", "La Paz "),
new State("SV", "UN", "La Union "),
new State("SV", "MO", "Morazan "),
new State("SV", "SM", "San Miguel "),
new State("SV", "SS", "San Salvador"),
new State("SV", "SV", "San Vicente "),
new State("SV", "SA", "Santa Ana "),
new State("SV", "SO", "Sonsonate "),
new State("SV", "US", "Usulutan "),
new State("SZ", "HH", "Hhohho"),
new State("SZ", "LU", "Lubombo"),
new State("SZ", "MA", "Manzini"),
new State("SZ", "SH", "Shiselweni"),
new State("TH", "37", "Amnat Charoen"),
new State("TH", "15", "Ang Thong"),
new State("TH", "10", "Bangkok Metropolis"),
new State("TH", "38", "Bueng Kan"),
new State("TH", "31", "Buri Ram"),
new State("TH", "24", "Chachoengsao"),
new State("TH", "18", "Chai Nat"),
new State("TH", "36", "Chaiyaphum"),
new State("TH", "22", "Chanthaburi"),
new State("TH", "50", "Chiang Mai"),
new State("TH", "57", "Chiang Rai"),
new State("TH", "20", "Chon Buri"),
new State("TH", "86", "Chumphon"),
new State("TH", "46", "Kalasin"),
new State("TH", "62", "Kamphaeng Phet"),
new State("TH", "71", "Kanchanaburi"),
new State("TH", "40", "Khon Kaen"),
new State("TH", "81", "Krabi"),
new State("TH", "52", "Lampang"),
new State("TH", "51", "Lamphun"),
new State("TH", "42", "Loei"),
new State("TH", "16", "Lop Buri"),
new State("TH", "58", "Mae Hong Son"),
new State("TH", "44", "Maha Sarakham"),
new State("TH", "49", "Mukdahan"),
new State("TH", "26", "Nakhon Nayok"),
new State("TH", "73", "Nakhon Pathom"),
new State("TH", "48", "Nakhon Phanom"),
new State("TH", "30", "Nakhon Ratchasima"),
new State("TH", "60", "Nakhon Sawan"),
new State("TH", "80", "Nakhon Si Thammarat"),
new State("TH", "55", "Nan"),
new State("TH", "96", "Narathiwat"),
new State("TH", "39", "Nong Bua Lam Phu"),
new State("TH", "43", "Nong Khai"),
new State("TH", "12", "Nonthaburi"),
new State("TH", "13", "Pathum Thani"),
new State("TH", "94", "Pattani"),
new State("TH", "82", "Phangnga"),
new State("TH", "93", "Phatthalung"),
new State("TH", "56", "Phayao"),
new State("TH", "67", "Phetchabun"),
new State("TH", "76", "Phetchaburi"),
new State("TH", "66", "Phichit"),
new State("TH", "65", "Phitsanulok"),
new State("TH", "14", "Phra Nakhon Si Ayutthaya"),
new State("TH", "54", "Phrae"),
new State("TH", "83", "Phuket"),
new State("TH", "25", "Prachin Buri"),
new State("TH", "77", "Prachuap Khiri Khan"),
new State("TH", "85", "Ranong"),
new State("TH", "70", "Ratchaburi"),
new State("TH", "21", "Rayong"),
new State("TH", "45", "Roi Et"),
new State("TH", "27", "Sa Kaeo"),
new State("TH", "47", "Sakon Nakhon"),
new State("TH", "11", "Samut Prakan"),
new State("TH", "74", "Samut Sakhon"),
new State("TH", "75", "Samut Songkhram"),
new State("TH", "19", "Saraburi"),
new State("TH", "91", "Satun"),
new State("TH", "33", "Si Sa Ket"),
new State("TH", "17", "Sing Buri"),
new State("TH", "90", "Songkhla"),
new State("TH", "64", "Sukhothai"),
new State("TH", "72", "Suphan Buri"),
new State("TH", "84", "Surat Thani"),
new State("TH", "32", "Surin"),
new State("TH", "63", "Tak"),
new State("TH", "92", "Trang"),
new State("TH", "23", "Trat"),
new State("TH", "34", "Ubon Ratchathani"),
new State("TH", "41", "Udon Thani"),
new State("TH", "61", "Uthai Thani"),
new State("TH", "53", "Uttaradit"),
new State("TH", "95", "Yala"),
new State("TH", "35", "Yasothon"),
new State("TL", "AL", "Aileu"),
new State("TL", "AN", "Ainaro"),
new State("TL", "BA", "Baucau"),
new State("TL", "BO", "Bobonaro"),
new State("TL", "CO", "Cova Lima"),
new State("TL", "DI", "Dili"),
new State("TL", "ER", "Ermera"),
new State("TL", "LA", "Lautem"),
new State("TL", "LI", "Liquica"),
new State("TL", "MT", "Manatuto"),
new State("TL", "MF", "Manufahi"),
new State("TL", "OE", "Oecussi"),
new State("TL", "VI", "Viqueque"),
new State("TN", "12", "Ariana"),
new State("TN", "31", "Beja"),
new State("TN", "13", "Ben Arous"),
new State("TN", "23", "Bizerte"),
new State("TN", "81", "Gabes"),
new State("TN", "71", "Gafsa"),
new State("TN", "32", "Jendouba"),
new State("TN", "41", "Kairouan"),
new State("TN", "42", "Kasserine"),
new State("TN", "73", "Kebili"),
new State("TN", "33", "Le Kef"),
new State("TN", "53", "Mahdia"),
new State("TN", "14", "Manouba"),
new State("TN", "82", "Medenine"),
new State("TN", "52", "Monastir"),
new State("TN", "21", "Nabeul"),
new State("TN", "61", "Sfax"),
new State("TN", "43", "Sidi Bou Zid"),
new State("TN", "34", "Siliana"),
new State("TN", "51", "Sousse"),
new State("TN", "83", "Tataouine"),
new State("TN", "72", "Tozeur"),
new State("TN", "11", "Tunis"),
new State("TN", "22", "Zaghouan"),
new State("TO", "01", "Eua"),
new State("TO", "02", "Ha'apia"),
new State("TO", "03", "Niuas"),
new State("TO", "04", "Tongatapu"),
new State("TO", "05", "Vava'u"),
new State("TT", "ARI", "Arima"),
new State("TT", "CHA", "Chaguanas"),
new State("TT", "CTT", "Couva-Tabaquite-Talparo"),
new State("TT", "DMN", "Diego Martin"),
new State("TT", "MRC", "Mayaro-Rio Claro"),
new State("TT", "PED", "Penal-Debe"),
new State("TT", "PTF", "Point Fortin"),
new State("TT", "POS", "Port of Spain"),
new State("TT", "PRT", "Princes Town"),
new State("TT", "SFO", "San Fernando"),
new State("TT", "SJL", "San Juan-Laventille"),
new State("TT", "SGE", "Sangre Grande"),
new State("TT", "SIP", "Siparia"),
new State("TT", "TOB", "Tobago"),
new State("TT", "TUP", "Tunapuna-Piarco"),
new State("TV", "FUN", "Funafuti"),
new State("TV", "NMG", "Nanumanga"),
new State("TV", "NMA", "Nanumea"),
new State("TV", "NIT", "Niutao"),
new State("TV", "NUI", "Nui"),
new State("TV", "NKF", "Nukufetau"),
new State("TV", "NKL", "Nukulaelae"),
new State("TV", "VAI", "Vaitupu"),
new State("TZ", "ARU", "Arusha"),
new State("TZ", "DAR", "Dar es Salaam"),
new State("TZ", "DOD", "Dodoma"),
new State("TZ", "GEI", "Geita"),
new State("TZ", "IRI", "Iringa"),
new State("TZ", "KAG", "Kagera"),
new State("TZ", "KAT", "Katavi"),
new State("TZ", "KIG", "Kigoma"),
new State("TZ", "KIL", "Kilimanjaro"),
new State("TZ", "LIN", "Lindi"),
new State("TZ", "MAN", "Manyara"),
new State("TZ", "MAR", "Mara"),
new State("TZ", "MBE", "Mbeya"),
new State("TZ", "MOR", "Morogoro"),
new State("TZ", "MTW", "Mtwara"),
new State("TZ", "MWA", "Mwanza"),
new State("TZ", "NJO", "Njombe"),
new State("TZ", "PEN", "Pemba North"),
new State("TZ", "PES", "Pemba South"),
new State("TZ", "PWA", "Pwani"),
new State("TZ", "RUK", "Rukwa"),
new State("TZ", "RUV", "Ruvuma"),
new State("TZ", "SHI", "Shinyanga"),
new State("TZ", "SIM", "Simiyu"),
new State("TZ", "SIN", "Singida"),
new State("TZ", "SON", "Songwe"),
new State("TZ", "TAB", "Tabora"),
new State("TZ", "TAN", "Tanga"),
new State("TZ", "ZAN", "Zanzibar North"),
new State("TZ", "ZAS", "Zanzibar South"),
new State("TZ", "ZUW", "Zanzibar Urban West"),
new State("UA", "43", "Avtonomna Respublika Krym"),
new State("UA", "71", "Cherkaska oblast"),
new State("UA", "74", "Chernihivska oblast"),
new State("UA", "77", "Chernivetska oblast"),
new State("UA", "12", "Dnipropetrovska oblast"),
new State("UA", "14", "Donetska oblast"),
new State("UA", "26", "Ivano-Frankivska oblast"),
new State("UA", "63", "Kharkivska oblast"),
new State("UA", "65", "Khersonska oblast"),
new State("UA", "68", "Khmelnytska oblast"),
new State("UA", "35", "Kirovohradska oblast"),
new State("UA", "32", "Kyivska oblast"),
new State("UA", "09", "Luhanska oblast"),
new State("UA", "46", "Lvivska oblast"),
new State("UA", "48", "Mykolaivska oblast"),
new State("UA", "51", "Odeska oblast"),
new State("UA", "53", "Poltavska oblast"),
new State("UA", "56", "Rivnenska oblast"),
new State("UA", "59", "Sumska oblast"),
new State("UA", "61", "Ternopilska oblast"),
new State("UA", "05", "Vinnytska oblast"),
new State("UA", "07", "Volynska oblast"),
new State("UA", "21", "Zakarpatska oblast"),
new State("UA", "23", "Zaporizka oblast"),
new State("UA", "18", "Zhytomyrska oblast"),
new State("US", "AL", "Alabama"),
new State("US", "AK", "Alaska"),
new State("US", "AZ", "Arizona"),
new State("US", "AR", "Arkansas"),
new State("US", "CA", "California"),
new State("US", "CO", "Colorado"),
new State("US", "CT", "Connecticut"),
new State("US", "DE", "Delaware"),
new State("US", "DC", "District of Columbia"),
new State("US", "FL", "Florida"),
new State("US", "GA", "Georgia"),
new State("US", "HI", "Hawaii"),
new State("US", "ID", "Idaho"),
new State("US", "IL", "Illinois"),
new State("US", "IN", "Indiana"),
new State("US", "IA", "Iowa"),
new State("US", "KS", "Kansas"),
new State("US", "KY", "Kentucky"),
new State("US", "LA", "Louisiana"),
new State("US", "ME", "Maine"),
new State("US", "MD", "Maryland"),
new State("US", "MA", "Massachusetts"),
new State("US", "MI", "Michigan"),
new State("US", "MN", "Minnesota"),
new State("US", "MS", "Mississippi"),
new State("US", "MO", "Missouri"),
new State("US", "MT", "Montana"),
new State("US", "NE", "Nebraska"),
new State("US", "NV", "Nevada"),
new State("US", "NH", "New Hampshire"),
new State("US", "NJ", "New Jersey"),
new State("US", "NM", "New Mexico"),
new State("US", "NY", "New York"),
new State("US", "NC", "North Carolina"),
new State("US", "ND", "North Dakota"),
new State("US", "OH", "Ohio"),
new State("US", "OK", "Oklahoma"),
new State("US", "OR", "Oregon"),
new State("US", "PA", "Pennsylvania"),
new State("US", "PR", "Puerto Rico"),
new State("US", "RI", "Rhode Island"),
new State("US", "SC", "South Carolina"),
new State("US", "SD", "South Dakota"),
new State("US", "TN", "Tennessee"),
new State("US", "TX", "Texas"),
new State("US", "UT", "Utah"),
new State("US", "VT", "Vermont"),
new State("US", "VA", "Virginia"),
new State("US", "WA", "Washington"),
new State("US", "WV", "West Virginia"),
new State("US", "WI", "Wisconsin"),
new State("US", "WY", "Wyoming"),
new State("UY", "ART", "Artigas"),
new State("UY", "CAN", "Canelones"),
new State("UY", "CER", "Cerro Largo"),
new State("UY", "COL", "Colonia"),
new State("UY", "DUR", "Durazno"),
new State("UY", "FLO", "Flores"),
new State("UY", "FLA", "Florida"),
new State("UY", "LAV", "Lavalleja"),
new State("UY", "MAL", "Maldonado"),
new State("UY", "MON", "Montevideo"),
new State("UY", "PAY", "Paysandu"),
new State("UY", "RIO", "Rio Negro"),
new State("UY", "RIV", "Rivera"),
new State("UY", "ROC", "Rocha"),
new State("UY", "SAL", "Salto"),
new State("UY", "SAN", "San Jose"),
new State("VA", "VA", "Holy See"),
new State("VC", "01", "Charlotte"),
new State("VC", "06", "Grenadines"),
new State("VC", "02", "Saint Andrew"),
new State("VC", "03", "Saint David"),
new State("VC", "04", "Saint George"),
new State("VC", "05", "Saint Patrick"),
new State("VE", "Z", "Amazonas"),
new State("VE", "B", "Anzoategui"),
new State("VE", "C", "Apure"),
new State("VE", "D", "Aragua"),
new State("VE", "E", "Barinas"),
new State("VE", "F", "Bolivar"),
new State("VE", "A", "Capital District"),
new State("VE", "G", "Carabobo"),
new State("VE", "H", "Cojedes"),
new State("VE", "Y", "Delta Amacuro"),
new State("VE", "I", "Falcon"),
new State("VE", "W", "Federal Dependencies"),
new State("VE", "J", "Guarico"),
new State("VE", "K", "Lara"),
new State("VE", "L", "Merida"),
new State("VE", "M", "Miranda"),
new State("VE", "N", "Monagas"),
new State("VE", "O", "Nueva Esparta"),
new State("VE", "P", "Portuguesa"),
new State("VE", "R", "Sucre"),
new State("VE", "S", "Tachira"),
new State("VE", "T", "Trujillo"),
new State("VE", "X", "Vargas"),
new State("VE", "U", "Yaracuy"),
new State("VE", "V", "Zulia"),
new State("VN", "44", "An Giang"),
new State("VN", "43", "Ba Ria-Vung Tau"),
new State("VN", "53", "Bac Can"),
new State("VN", "54", "Bac Giang"),
new State("VN", "55", "Bac Lieu"),
new State("VN", "56", "Bac Ninh"),
new State("VN", "50", "Ben Tre"),
new State("VN", "31", "Binh Dinh"),
new State("VN", "57", "Binh Duong"),
new State("VN", "58", "Binh Phuoc"),
new State("VN", "40", "Binh Thuan"),
new State("VN", "59", "Ca Mau"),
new State("VN", "CT", "Can Tho"),
new State("VN", "04", "Cao Bang"),
new State("VN", "DN", "Da Nang"),
new State("VN", "33", "Dac Lac"),
new State("VN", "72", "Dac Nong"),
new State("VN", "71", "Dien Bien"),
new State("VN", "39", "Dong Nai"),
new State("VN", "45", "Dong Thap"),
new State("VN", "30", "Gia Lai"),
new State("VN", "03", "Ha Giang"),
new State("VN", "63", "Ha Nam"),
new State("VN", "23", "Ha Tinh"),
new State("VN", "61", "Hai Duong"),
new State("VN", "HP", "Haiphong"),
new State("VN", "HN", "Hanoi"),
new State("VN", "73", "Hau Giang"),
new State("VN", "SG", "Ho Chi Minh"),
new State("VN", "14", "Hoa Binh"),
new State("VN", "66", "Hung Yen"),
new State("VN", "34", "Khanh Hoa"),
new State("VN", "47", "Kien Giang"),
new State("VN", "28", "Kon Tum"),
new State("VN", "01", "Lai Chau"),
new State("VN", "35", "Lam Dong"),
new State("VN", "09", "Lang Son"),
new State("VN", "02", "Lao Cai"),
new State("VN", "41", "Long An"),
new State("VN", "67", "Nam Dinh"),
new State("VN", "22", "Nghe An"),
new State("VN", "18", "Ninh Binh"),
new State("VN", "36", "Ninh Thuan"),
new State("VN", "68", "Phu Tho"),
new State("VN", "32", "Phu Yen"),
new State("VN", "24", "Quang Binh"),
new State("VN", "27", "Quang Nam"),
new State("VN", "29", "Quang Ngai"),
new State("VN", "13", "Quang Ninh"),
new State("VN", "25", "Quang Tri"),
new State("VN", "52", "Soc Trang"),
new State("VN", "05", "Son La"),
new State("VN", "37", "Tay Ninh"),
new State("VN", "20", "Thai Binh"),
new State("VN", "69", "Thai Nguyen"),
new State("VN", "21", "Thanh Hoa"),
new State("VN", "26", "Thua Thien-Hue"),
new State("VN", "46", "Tien Giang"),
new State("VN", "51", "Tra Vinh"),
new State("VN", "07", "Tuyen Quang"),
new State("VN", "49", "Vinh Long"),
new State("VN", "70", "Vinh Phuc"),
new State("VN", "06", "Yen Bai"),
new State("VU", "MAP", "Malampa"),
new State("VU", "PAM", "Penama"),
new State("VU", "SAM", "Sanma"),
new State("VU", "SEE", "Shefa"),
new State("VU", "TAE", "Tafea"),
new State("VU", "TOB", "Torba"),
new State("WS", "AA", "A'ana"),
new State("WS", "AL", "Aiga-i-le-Tai"),
new State("WS", "AT", "Atua"),
new State("WS", "FA", "Fa'asaleleaga"),
new State("WS", "GE", "Gaga'emauga"),
new State("WS", "GI", "Gagaifomauga"),
new State("WS", "PA", "Palauli"),
new State("WS", "SA", "Satupa'itea"),
new State("WS", "TU", "Tuamasaga"),
new State("WS", "VF", "Va'a-o-Fonoti"),
new State("WS", "VS", "Vaisigano"),
new State("ZA", "EC", "Eastern Cape"),
new State("ZA", "FS", "Free State"),
new State("ZA", "GT", "Gauteng"),
new State("ZA", "NL", "KwaZulu-Natal"),
new State("ZA", "LP", "Limpopo"),
new State("ZA", "MP", "Mpumalanga"),
new State("ZA", "NW", "North West"),
new State("ZA", "NC", "Northern Cape"),
new State("ZA", "WC", "Western Cape"),
new State("ZM", "CEN", "Central"),
new State("ZM", "COP", "Copperbelt"),
new State("ZM", "EAS", "Eastern"),
new State("ZM", "LUA", "Luapula"),
new State("ZM", "LUS", "Lusaka"),
new State("ZM", "MUC", "Muchinga"),
new State("ZM", "NOR", "Northern"),
new State("ZM", "NOW", "North-Western"),
new State("ZM", "SOU", "Southern"),
new State("ZM", "WES", "Western"),
new State("ZM", "ZAM", "Zambia"),
new State("ZW", "BU", "Bulawayo"),
new State("ZW", "HA", "Harare"),
new State("ZW", "MA", "Manicaland"),
new State("ZW", "MC", "Mashonaland Central"),
new State("ZW", "ME", "Mashonaland East"),
new State("ZW", "MW", "Mashonaland West"),
new State("ZW", "MV", "Masvingo"),
new State("ZW", "MN", "Matabeleland North"),
new State("ZW", "MS", "Matabeleland South"),
new State("ZW", "MI", "Midlands")
            };
            return states;
        }

        private static Boolean CheckCountryCodes(string countryCode)
        {
            var supportedCountryCodes = new List<string>()
            {
"AD",
"AE",
"AG",
"AL",
"AR",
"AT",
"AU",
"BA",
"BE",
"BG",
"BO",
"BR",
"BS",
"BW",
"BY",
"BZ",
"CA",
"CH",
"CL",
"CN",
"CO",
"CR",
"CU",
"CV",
"CY",
"CZ",
"DC",
"DE",
"DK",
"DM",
"DO",
"DZ",
"EC",
"EE",
"EG",
"ES",
"FI",
"FJ",
"FM",
"FR",
"GB",
"GD",
"GL",
"GR",
"GT",
"GY",
"HN",
"HR",
"HT",
"IE",
"IN",
"IS",
"IT",
"JP",
"KE",
"KI",
"KN",
"KZ",
"LC",
"LI",
"LS",
"LU",
"LV",
"MA",
"MG",
"MH",
"MU",
"MV",
"MW",
"MX",
"MZ",
"NA",
"NI",
"NL",
"NO",
"NR",
"NZ",
"PA",
"PE",
"PG",
"PH",
"PL",
"PT",
"PW",
"PY",
"QA",
"RU",
"SB",
"SE",
"SG",
"SM",
"SN",
"SR",
"SV",
"SZ",
"TH",
"TL",
"TN",
"TO",
"TT",
"TV",
"TZ",
"UA",
"US",
"UY",
"VA",
"VC",
"VE",
"VN",
"VU",
"WS",
"ZA",
"ZM",
"ZW"
            };

            if(supportedCountryCodes.Contains(countryCode))
            { 
                return true;
            }
            else
            { 
                return false;
            }
        }
    }
}
